#!/usr/bin/env python3
"""warden_hookgen — hook fan-in (Tink F299).

Every script registered on a hook moment costs its own process. Arming F294
made `Stop` carry three commands, two of them Python, so a turn end started two
interpreters that almost always do nothing. The fix is not to merge sources by
hand — that entangles two features permanently — but to make the merge
*computed*: authored scripts stay separate files, and Warden generates one
entrypoint per (moment, runtime) that runs them in a single interpreter.

Two sources feed the manifest and this module merges them:

  1. **Declarations scanned out of hook-script sources.** A script opts in with
     a `# warden-hook: <Moment>` line in its header and exposes
     `warden_hook(event) -> dict | None`. The declaration is a *comment* on
     purpose — a module-level constant would require importing the file to
     learn whether it should be imported, so a script with a broken import
     could never be seen at all. Text-scanned, exactly like the `when::` /
     `where::` fields Warden already reads out of authored rulesets.
  2. **A `hooks:` block in the user's `config.yaml`.** The only file the user
     edits. Adding a hook to a moment that already has an entrypoint is one
     line there plus a `warden compile` — no `settings.json` edit, no manifest
     edit, no other script touched.

Everything this module writes lands under `~/.warden/` beside `rules-ir.json`
and `rules_all.py`: `hooks-ir.json` (the derived manifest) and one
`hook_<moment>.py` per moment. All carry the generated-header contract and are
never hand-edited. `~/.claude/settings.json` gets one static line per moment,
ever, written by hand — Warden never touches it.

Composition is by import, not by source concatenation: appending independent
files into one namespace collides on shared top-level names, runs each file's
side effects in an order nobody chose, and merges their `__main__` blocks into
nonsense. Importing costs essentially nothing once the interpreter is up (the
interpreter start is the recoverable cost, not module init) and keeps stack
traces pointing at the real file and line.

Failure isolation is the load-bearing property: a module that raises is
skipped, its failure reported alongside whatever the survivors returned, and
the remaining modules still run and can still block. Fan-in must not make
co-registration a shared failure domain — one script's bug silently disarming
every other hook on the moment would be strictly worse than the status quo.
"""
from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path

SCHEMA = 1
ENTRYPOINT = "warden_hook"

# The declaration must sit in the file header, so a scan reads a few lines
# rather than whole sources, and so the declaration stays where a reader looks.
HEADER_LINES = 40
DECL_RE = re.compile(r"^#\s*warden-hook:\s*([A-Za-z][A-Za-z0-9]*)\s*$")

# Claude Code's hook events. A declaration naming anything else is a typo the
# scan reports rather than silently generating an entrypoint nothing registers.
MOMENTS = ("PreToolUse", "PostToolUse", "Notification", "UserPromptSubmit",
           "Stop", "SubagentStop", "PreCompact", "SessionStart", "SessionEnd")

GENERATED_HEADER = "# GENERATED by warden_hookgen.py — do not edit."


def moment_slug(moment: str) -> str:
    """`Stop` → `stop`; the generated file is `hook_<slug>.py`."""
    return re.sub(r"(?<!^)(?=[A-Z])", "_", moment).lower()


def module_name(path: Path) -> str:
    """A python identifier naming `path`'s module inside the entrypoint."""
    return re.sub(r"\W", "_", path.stem)


# ── source 1: declarations scanned out of hook scripts ───────────────────────

def scan_roots(corpus: Path) -> list[Path]:
    """Where hook scripts live. Bounded on purpose — a hook script is either a
    skill script in the corpus or a loose script in `~/.claude`."""
    roots = [corpus / "skills", Path.home() / ".claude"]
    return [r for r in roots if r.is_dir()]


def _declared_moment(path: Path) -> str | None:
    try:
        with path.open("r", encoding="utf-8", errors="replace") as fh:
            for _ in range(HEADER_LINES):
                line = fh.readline()
                if not line:
                    return None
                m = DECL_RE.match(line.rstrip("\n"))
                if m:
                    return m.group(1)
    except OSError:
        return None
    return None


def scan_declarations(roots: list[Path]) -> tuple[list[dict], list[str]]:
    """Every `# warden-hook: <Moment>` declaration under `roots`, plus warnings.

    Only `.py` files are scanned: a declaration is a promise to expose
    `warden_hook(event)`, which only a Python module can keep. A bash hook
    joins through the `config.yaml` `hooks:` block as a `command:` instead —
    it cannot share an interpreter, so there is nothing for a declaration to
    buy it.
    """
    found: list[dict] = []
    warnings: list[str] = []
    seen: set[Path] = set()
    for root in roots:
        for path in sorted(root.rglob("*.py")):
            real = path.resolve()
            if real in seen:
                continue            # ~/.claude/skills symlinks into the corpus
            seen.add(real)
            moment = _declared_moment(path)
            if moment is None:
                continue
            if moment not in MOMENTS:
                warnings.append(f"{path}: unknown moment '{moment}' — ignored "
                                f"(expected one of {', '.join(MOMENTS)})")
                continue
            found.append({"moment": moment, "runtime": "python",
                          "path": str(real), "module": module_name(real),
                          "source": "declaration"})
    return found, warnings


# ── source 2: the user's config.yaml `hooks:` block ──────────────────────────

def config_hooks(config_path: Path) -> tuple[list[dict], list[str]]:
    """The `hooks:` block of the user's config.yaml, as manifest entries.

        hooks:
          Stop:
            - script: ~/bin/my-stop-check.py   # python, joins the interpreter
            - command: bash ~/bin/notify.sh    # anything else, spawned

    A `script:` entry needs no `# warden-hook:` declaration — naming it here
    IS the declaration. A `command:` entry is spawned as a subprocess by the
    generated entrypoint rather than requiring its own `settings.json` line:
    that costs the same process either way, and keeps "add a hook without
    touching anything else" true for non-Python hooks too.
    """
    if not config_path.is_file():
        return [], []
    import yaml
    try:
        data = yaml.safe_load(config_path.read_text(encoding="utf-8")) or {}
    except yaml.YAMLError as e:
        return [], [f"{config_path}: unreadable YAML — {e}"]
    block = data.get("hooks") or {}
    if not isinstance(block, dict):
        return [], [f"{config_path}: `hooks:` must be a mapping of moment → list"]

    out: list[dict] = []
    warnings: list[str] = []
    for moment, entries in block.items():
        if moment not in MOMENTS:
            warnings.append(f"{config_path}: unknown moment '{moment}' — ignored")
            continue
        for entry in (entries or []):
            if isinstance(entry, str):
                entry = {"command": entry}
            if not isinstance(entry, dict):
                warnings.append(f"{config_path}: {moment}: entry is not a mapping")
                continue
            if entry.get("script"):
                path = Path(str(entry["script"])).expanduser()
                if not path.is_file():
                    warnings.append(f"{config_path}: {moment}: no such script — {path}")
                    continue
                out.append({"moment": moment, "runtime": "python",
                            "path": str(path.resolve()),
                            "module": module_name(path),
                            "source": "config.yaml"})
            elif entry.get("command"):
                out.append({"moment": moment, "runtime": "command",
                            "command": str(entry["command"]),
                            "source": "config.yaml"})
            else:
                warnings.append(f"{config_path}: {moment}: entry has neither "
                                "`script:` nor `command:`")
    return out, warnings


# ── manifest ─────────────────────────────────────────────────────────────────

def build_manifest(corpus: Path, config_path: Path | None = None,
                   roots: list[Path] | None = None) -> tuple[dict, list[str]]:
    """Merge both sources into the derived manifest. Declarations come first
    within a moment (sorted by module, so the order is a property of the corpus
    rather than of filesystem walk order), then config entries in the order the
    user wrote them — a user-added hook runs after the ones already there.

    `roots` overrides where declarations are scanned; the default reaches into
    `~/.claude`, which a test must not depend on."""
    if config_path is None:
        config_path = Path.home() / ".config/anchor-system/warden/config.yaml"
    declared, warnings = scan_declarations(roots if roots is not None
                                           else scan_roots(corpus))
    configured, cfg_warnings = config_hooks(config_path)
    warnings += cfg_warnings

    moments: dict[str, list[dict]] = {}
    for e in sorted(declared, key=lambda e: (e["moment"], e["module"])):
        moments.setdefault(e["moment"], []).append(e)
    for e in configured:
        entries = moments.setdefault(e["moment"], [])
        if e["runtime"] == "python" and any(
                x.get("path") == e["path"] for x in entries):
            continue                # already declared in its own source
        entries.append(e)

    manifest = {
        "schema": SCHEMA,
        "generated_by": "warden_hookgen.py — do not edit; run `warden compile`",
        "entrypoint": ENTRYPOINT,
        "config": str(config_path),
        "moments": moments,
    }
    return manifest, warnings


# ── the generated entrypoint ─────────────────────────────────────────────────

_TEMPLATE = '''#!/usr/bin/env python3
{header}
# Moment: {moment}. One interpreter for {n} hook(s); regenerate with `warden compile`.
#
# Each module runs inside its own guard: a module that raises is skipped, its
# failure reported alongside the surviving decisions rather than swallowed, and
# the remaining modules still run and can still block. Any block wins and every
# blocking reason is included, so a hook's outcome never depends on what else
# happens to be registered ahead of it.
import json
import sys

MOMENT = {moment!r}
MODULES = {modules!r}
COMMANDS = {commands!r}
LOG = {log!r}


def _log(note):
    try:
        import time
        with open(LOG, "a", encoding="utf-8") as fh:
            fh.write("%s %s %s\\n" % (time.strftime("%Y-%m-%dT%H:%M:%S"), MOMENT, note))
    except OSError:
        pass


def _call(name, path, event):
    """Run one module's entrypoint. Returns (output, failure-note)."""
    import importlib.util
    try:
        spec = importlib.util.spec_from_file_location("wardenhook_" + name, path)
        if spec is None or spec.loader is None:
            return None, "%s: not importable (%s)" % (name, path)
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        fn = getattr(mod, {entrypoint!r}, None)
        if fn is None:
            return None, "%s: no %s() entrypoint" % (name, {entrypoint!r})
        return fn(event), None
    except SystemExit as e:
        # A script that exits cleanly said nothing; a non-zero exit is a fault.
        code = e.code or 0
        return None, None if code == 0 else "%s: exited %s" % (name, code)
    except BaseException as e:
        return None, "%s: %s: %s" % (name, type(e).__name__, e)


def _spawn(command, raw):
    """Run one non-Python hook as a subprocess. Returns (output, failure-note).
    Exit 2 is Claude Code's block convention; stderr carries the reason."""
    import subprocess
    try:
        p = subprocess.run(command, shell=True, input=raw, text=True,
                           capture_output=True, timeout=30)
    except BaseException as e:
        return None, "%s: %s: %s" % (command, type(e).__name__, e)
    if p.returncode == 2:
        return {{"decision": "block", "reason": (p.stderr or "").strip() or command}}, None
    out = (p.stdout or "").strip()
    if out.startswith("{{"):
        try:
            return json.loads(out), None
        except ValueError:
            pass
    return None, None


def main():
    raw = sys.stdin.read()
    try:
        event = json.loads(raw or "{{}}")
    except ValueError:
        event = {{}}

    blocks, notes, other = [], [], []
    for name, path in MODULES:
        out, note = _call(name, path, event)
        if note:
            notes.append(note)
        if isinstance(out, dict) and out:
            (blocks if out.get("decision") == "block" else other).append(out)
    for command in COMMANDS:
        out, note = _spawn(command, raw)
        if note:
            notes.append(note)
        if isinstance(out, dict) and out:
            (blocks if out.get("decision") == "block" else other).append(out)

    for note in notes:
        _log(note)

    if blocks:
        reason = "\\n\\n".join(str(b.get("reason") or "") for b in blocks if b.get("reason"))
        if notes:
            reason += "\\n\\n[warden hook fan-in] " + "; ".join(notes)
        print(json.dumps({{"decision": "block", "reason": reason}}))
        return 0
    if other:
        merged = {{}}
        for o in other:
            for k, v in o.items():
                if k in merged and isinstance(v, str) and isinstance(merged[k], str):
                    merged[k] = merged[k] + "\\n" + v
                else:
                    merged[k] = v
        print(json.dumps(merged))
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except BaseException:
        # Fail open, always: a hook that can trap a session is worse than no
        # hook. Whatever went wrong is already in the log.
        sys.exit(0)
'''


def emit_entrypoint(moment: str, entries: list[dict], log_path: Path) -> str:
    modules = [(e["module"], e["path"]) for e in entries if e["runtime"] == "python"]
    commands = [e["command"] for e in entries if e["runtime"] == "command"]
    return _TEMPLATE.format(header=GENERATED_HEADER, moment=moment,
                            n=len(modules) + len(commands), modules=modules,
                            commands=commands, entrypoint=ENTRYPOINT,
                            log=str(log_path))


# ── generate ─────────────────────────────────────────────────────────────────

def generate(out: Path, corpus: Path, config_path: Path | None = None,
             roots: list[Path] | None = None) -> dict:
    """Write the manifest and one entrypoint per moment into `out`.

    A moment whose entrypoint already exists is regenerated even when it has
    dropped to zero hooks — it is left as an inert pass-through rather than
    deleted, because `settings.json` may still point at it and a missing file
    is a hook error on every turn.
    """
    manifest, warnings = build_manifest(corpus, config_path, roots)
    out.mkdir(parents=True, exist_ok=True)
    log_path = out / "hookgen.log"

    moments = dict(manifest["moments"])
    for existing in out.glob("hook_*.py"):
        for m in MOMENTS:
            if existing.name == f"hook_{moment_slug(m)}.py":
                moments.setdefault(m, [])

    written = []
    for moment, entries in sorted(moments.items()):
        path = out / f"hook_{moment_slug(moment)}.py"
        tmp = path.with_name(path.name + ".tmp")
        tmp.write_text(emit_entrypoint(moment, entries, log_path), encoding="utf-8")
        os.replace(tmp, path)
        path.chmod(0o755)
        written.append(path)

    mf = out / "hooks-ir.json"
    tmp = mf.with_name(mf.name + ".tmp")
    tmp.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    os.replace(tmp, mf)

    return {"manifest": mf, "entrypoints": written, "warnings": warnings,
            "hooks": sum(len(v) for v in manifest["moments"].values()),
            "moments": len(manifest["moments"])}


def main(argv=None) -> int:
    import argparse
    from warden_root import corpus_root
    ap = argparse.ArgumentParser(
        prog="warden-hookgen",
        description="Derive the hook manifest and generate one entrypoint per moment.")
    ap.add_argument("--out", default=None, help="output dir (default: ~/.warden)")
    ap.add_argument("--corpus", default=None, help="corpus root to scan for declarations")
    ap.add_argument("--config", default=None, help="config.yaml holding the `hooks:` block")
    a = ap.parse_args(argv)

    out = Path(a.out).expanduser() if a.out else (Path.home() / ".warden")
    corpus = Path(a.corpus).expanduser() if a.corpus else corpus_root()
    config = Path(a.config).expanduser() if a.config else None
    stats = generate(out, corpus, config)
    for w in stats["warnings"]:
        print(f"warden-hookgen: WARNING — {w}", file=sys.stderr)
    print(f"warden-hookgen: {stats['hooks']} hook(s) across {stats['moments']} "
          f"moment(s) → {stats['manifest']}")
    for p in stats["entrypoints"]:
        print(p)
    return 0


if __name__ == "__main__":
    sys.exit(main())
