# GENERATED by warden_compile.py — do not edit.
# Source rulesets are authoritative; regenerate on rule change.
# anchor: all

import os
import subprocess
import time
import re
import json, os, time


def guard_R_fex_bundle_01(ctx):
    import datetime
    import json
    import re
    file = getattr(ctx, 'file', None)
    agent = getattr(ctx, 'agent', None)
    event = getattr(ctx, 'event', None)
    anchor = getattr(ctx, 'anchor', None)
    git = getattr(ctx, 'git', None)
    today = datetime.date.today()
    now = datetime.datetime.now()
    try:
        return bool((not re.search(r'^\d{4}-\d{2}-\d{2}-\d{4}$', file.name)))
    except Exception:
        return False


def guard_R_fex_bundle_02(ctx):
    import datetime
    import json
    import re
    file = getattr(ctx, 'file', None)
    agent = getattr(ctx, 'agent', None)
    event = getattr(ctx, 'event', None)
    anchor = getattr(ctx, 'anchor', None)
    git = getattr(ctx, 'git', None)
    today = datetime.date.today()
    now = datetime.datetime.now()
    try:
        return bool((len([f for f in dir.files if f.name == 'manifest.txt']) != 1))
    except Exception:
        return False


def guard_R_fex_pin_01(ctx):
    import datetime
    import json
    import re
    file = getattr(ctx, 'file', None)
    agent = getattr(ctx, 'agent', None)
    event = getattr(ctx, 'event', None)
    anchor = getattr(ctx, 'anchor', None)
    git = getattr(ctx, 'git', None)
    today = datetime.date.today()
    now = datetime.datetime.now()
    try:
        return bool((re.search(r'^\d{4}-\d{2}-\d{2}-\d{4}$', file.name) is None))
    except Exception:
        return False


def guard_R_fex_pin_02(ctx):
    import datetime
    import json
    import re
    file = getattr(ctx, 'file', None)
    agent = getattr(ctx, 'agent', None)
    event = getattr(ctx, 'event', None)
    anchor = getattr(ctx, 'anchor', None)
    git = getattr(ctx, 'git', None)
    today = datetime.date.today()
    now = datetime.datetime.now()
    try:
        return bool((not (anchor.root / 'snapshots' / file.name).is_dir()))
    except Exception:
        return False


def guard_R_fex_manifest_01(ctx):
    import datetime
    import json
    import re
    file = getattr(ctx, 'file', None)
    agent = getattr(ctx, 'agent', None)
    event = getattr(ctx, 'event', None)
    anchor = getattr(ctx, 'anchor', None)
    git = getattr(ctx, 'git', None)
    today = datetime.date.today()
    now = datetime.datetime.now()
    try:
        return bool((any(not re.match(r'^[a-z][a-z0-9_]*: .+$', l) for l in file.lines if l.strip())))
    except Exception:
        return False


def guard_R_fex_manifest_02(ctx):
    import datetime
    import json
    import re
    file = getattr(ctx, 'file', None)
    agent = getattr(ctx, 'agent', None)
    event = getattr(ctx, 'event', None)
    anchor = getattr(ctx, 'anchor', None)
    git = getattr(ctx, 'git', None)
    today = datetime.date.today()
    now = datetime.datetime.now()
    try:
        return bool((not all(re.search(r'^' + k + r':', file.text, re.M) for k in ['label', 'commit', 'branch', 'created'])))
    except Exception:
        return False


def guard_R_fex_manifest_03(ctx):
    import datetime
    import json
    import re
    file = getattr(ctx, 'file', None)
    agent = getattr(ctx, 'agent', None)
    event = getattr(ctx, 'event', None)
    anchor = getattr(ctx, 'anchor', None)
    git = getattr(ctx, 'git', None)
    today = datetime.date.today()
    now = datetime.datetime.now()
    try:
        return bool((re.search(r'^[a-z][a-z0-9_]*: /', file.text, re.M)))
    except Exception:
        return False


def body_R_backupguard_01(ctx):
    # The exemption is a LOCATION, not an identity. Warden resolves rules from
    # the anchor the session is working in and exposes no per-agent value, so
    # "only Atticus" is really "only a session operating from an anchor that
    # declares `masterguard`" — today, `SYS/Staff/Atticus/.anchor` alone. Any
    # agent cwd'd there is exempt; Atticus working elsewhere is not. That gap is
    # real and small, and stating it is better than implying a stronger claim.
    if "masterguard" in (getattr(ctx, "traits", None) or []):
        return []

    ev = getattr(ctx, "event", None)
    inp = getattr(ev, "input", None) or {}
    cmd = inp.get("command") or ""
    # Cheap reject first: this rule fires on every Bash call in the vault.
    if "/Volumes/" not in cmd:
        return []

    import os
    import re
    import shlex

    # Not a drive: `∑` is a symlink to `/` (the boot volume, governed by
    # everything else), and the two TimeMachine paths are the OS's own. Every
    # other name under /Volumes/ is treated as a backup drive whether or not
    # the catalog knows it — see the fail-closed note below.
    NOT_A_DRIVE = ("∑", "com.apple.TimeMachine.localsnapshots", ".timemachine")
    VOL = re.compile(r"^/Volumes/([^/]+)(/|$)")

    def vol_of(tok):
        m = VOL.match(tok.strip("'\"<>"))
        if not m:
            return None
        v = m.group(1)
        if v in NOT_A_DRIVE:
            return None
        return v

    def split(s):
        try:
            return shlex.split(s)
        except ValueError:
            return s.split()          # unparseable quoting — deny-side conservative

    SEPS = (";", "&&", "||", "|", "&")

    def segments(words, depth=0):
        """Simple commands, including those nested inside quoted payloads.

        Drive work reaches a drive through the bridge as
        `ssh host "tmux send-keys -t w 'rm -rf /Volumes/BLACK/x' Enter"`. After
        one shlex pass the remote command is ONE token, so a rule reading only
        top-level tokens would wave through exactly the calls that matter most.
        """
        cur = []
        for w in words:
            if w in SEPS:
                if cur:
                    yield cur
                cur = []
                continue
            cur.append(w)
            if depth < 3 and "/Volumes/" in w and vol_of(w) is None:
                inner = split(w)
                if inner != [w]:
                    for seg in segments(inner, depth + 1):
                        yield seg
        if cur:
            yield cur

    # Reading FROM a drive is always allowed — `ls`, `find`, `shasum`, `cat`,
    # and `cp /Volumes/BLACK/x /tmp/` are how the catalog gets measured at all.
    # So position matters and mere mention does not.
    DEST_LAST = ("cp", "mv", "rsync", "ditto", "install", "scp")
    ANY_ARG = ("rm", "rmdir", "unlink", "shred", "truncate", "mkdir", "touch",
               "chmod", "chown", "chflags", "ln", "mkfifo", "tee")
    # Whole-volume verbs. These take no destination in the ordinary sense and
    # would sail past the two lists above, while being the fastest way to
    # destroy a drive that exists. `newfs_*` and `asr restore` have no read
    # form at all, so any of them aimed at a drive is a write.
    ALWAYS_VOLUME = ("newfs_apfs", "newfs_hfs", "asr")
    # `diskutil` is the exception, and it is an ALLOWLIST rather than a
    # deny-list — same fail-closed direction as the volume names themselves.
    # A deny-list here was wrong on its first test: it carried `apfs`, which
    # swallowed `diskutil apfs listCryptoUsers`, the exact command T184 used to
    # establish that 10T and 8T each have one crypto user and no recovery key.
    # Denying the instrument the catalog is measured with is worse than useless
    # — it teaches the next agent to route around the guard.
    DISKUTIL_READ = ("info", "information", "list", "verifyvolume", "verifydisk",
                     "mount", "mountdisk", "unmount", "unmountdisk", "eject")
    APFS_READ = ("list", "listcryptousers", "listusers", "listsnapshots",
                 "listvolumegroups", "unlockvolume")

    # Glued redirects (`>/Volumes/...`) split so the target is its own token.
    flat = []
    for w in split(cmd):
        if w[:1] == ">" and len(w.lstrip(">")) > 0:
            flat.append(">>" if w[:2] == ">>" else ">")
            flat.append(w.lstrip(">"))
        else:
            flat.append(w)

    hits = []
    for seg in segments(flat):
        for k, w in enumerate(seg):
            if w in (">", ">>") and k + 1 < len(seg):
                v = vol_of(seg[k + 1])
                if v:
                    hits.append((v, "a shell redirect onto the drive"))
        base = os.path.basename(seg[0].strip("'\""))
        args = [a for a in seg[1:] if a not in (">", ">>")]
        nonflag = [a for a in args if a[:1] != "-"]
        if base in DEST_LAST and nonflag:
            v = vol_of(nonflag[-1])
            if v:
                hits.append((v, "`%s` writing ONTO the drive" % base))
        elif base in ANY_ARG:
            for a in args:
                v = vol_of(a)
                if v:
                    hits.append((v, "`%s` mutating a path on the drive" % base))
        elif base == "dd":
            for a in args:
                if a.startswith("of="):
                    v = vol_of(a[3:])
                    if v:
                        hits.append((v, "`dd of=` targeting the drive"))
        elif base in ("zip", "tar") and nonflag:
            v = vol_of(nonflag[0])
            if v:
                hits.append((v, "`%s` writing its archive onto the drive" % base))
        elif base in ALWAYS_VOLUME:
            for a in args:
                v = vol_of(a)
                if v:
                    hits.append((v, "`%s` operating on the whole volume" % base))
        elif base == "diskutil":
            verb = (nonflag[0].lower() if nonflag else "")
            if verb == "apfs":
                ok = len(nonflag) > 1 and nonflag[1].lower() in APFS_READ
            else:
                ok = verb in DISKUTIL_READ
            if not ok:
                for a in args:
                    v = vol_of(a)
                    if v:
                        hits.append((v, "`diskutil %s` — not one of the read-only "
                                        "subcommands the catalog is measured with"
                                        % (verb or "?")))

    if not hits:
        return []

    # The escape is for a volume that genuinely is not a backup drive — a
    # camera card, a scratch USB. The sentinel sits at the VOLUME ROOT, which
    # this rule denies writing to, so a walled-off agent cannot create its own
    # exemption: only Dan by hand, or Atticus, can place one.
    hits = [h for h in hits
            if not os.path.exists("/Volumes/%s/.not-a-backup" % h[0])]
    if not hits:
        return []

    vol, why = hits[0]
    return ["DENY: %s. /Volumes/%s/ is treated as one of the estate's backup "
            "drives, and those are Atticus's sole custody — Dan's ruling on ATT "
            "T182, 2026-08-21: one agent has the keys, nobody else does. This is "
            "not a permission you can raise; it is whose job it is. Hand the work "
            "over instead: `state drop ATT --source <you> --tag drive` with what "
            "you need written and why. If /Volumes/%s is genuinely NOT a backup "
            "drive (a camera card, a scratch USB), ask Dan or Atticus to place "
            "/Volumes/%s/.not-a-backup at its root and this rule goes quiet for "
            "it." % (why, vol, vol, vol)]


def body_R_backupguard_02(ctx):
    if "masterguard" in (getattr(ctx, "traits", None) or []):
        return []
    ev = getattr(ctx, "event", None)
    target = getattr(ev, "target", None) if ev else None
    if not target:
        return []
    import os
    import re
    NOT_A_DRIVE = ("∑", "com.apple.TimeMachine.localsnapshots", ".timemachine")
    # Resolve first: a symlink into a drive (`~/mnt10T -> /Volumes/10T`) reaches
    # the same bytes without the literal prefix. Cheap — one syscall — and only
    # available on this path, which is why the Bash rule above is string-based
    # and this one is not.
    try:
        real = os.path.realpath(target)
    except OSError:
        real = target
    m = re.match(r"^/Volumes/([^/]+)(/|$)", real)
    if not m or m.group(1) in NOT_A_DRIVE:
        return []
    vol = m.group(1)
    if os.path.exists("/Volumes/%s/.not-a-backup" % vol):
        return []
    return ["DENY: Write to /Volumes/%s/ — the estate's backup drives are "
            "Atticus's sole custody (ATT T182, Dan, 2026-08-21). Hand the work "
            "over with `state drop ATT --source <you> --tag drive`. If this "
            "volume is genuinely not a backup drive, ask Dan or Atticus to place "
            "/Volumes/%s/.not-a-backup at its root." % (vol, vol)]


def body_R_backupguard_03(ctx):
    if "masterguard" in (getattr(ctx, "traits", None) or []):
        return []
    ev = getattr(ctx, "event", None)
    target = getattr(ev, "target", None) if ev else None
    if not target:
        return []
    import os
    import re
    NOT_A_DRIVE = ("∑", "com.apple.TimeMachine.localsnapshots", ".timemachine")
    try:
        real = os.path.realpath(target)
    except OSError:
        real = target
    m = re.match(r"^/Volumes/([^/]+)(/|$)", real)
    if not m or m.group(1) in NOT_A_DRIVE:
        return []
    vol = m.group(1)
    if os.path.exists("/Volumes/%s/.not-a-backup" % vol):
        return []
    return ["DENY: Edit of a file on /Volumes/%s/ — the estate's backup drives "
            "are Atticus's sole custody (ATT T182, Dan, 2026-08-21). Hand the "
            "work over with `state drop ATT --source <you> --tag drive`. If this "
            "volume is genuinely not a backup drive, ask Dan or Atticus to place "
            "/Volumes/%s/.not-a-backup at its root." % (vol, vol)]


def body_R_code_mirror_01(ctx):
    ev = getattr(ctx, "event", None)
    target = getattr(ev, "target", None) if ev else None
    if not target:
        return []
    import json
    from pathlib import Path
    idx = Path.home() / ".config/anchor-system/mirror-routes.json"
    if not idx.is_file():
        return []
    try:
        routes = json.loads(idx.read_text()).get("routes", [])
    except Exception:
        return []
    try:
        t = Path(target).resolve()
    except OSError:
        t = Path(target)
    for e in routes:
        if e.get("direction") == "pull":
            continue  # repo side is the source on pull routes
        there = Path(e.get("there", ""))
        if t == there or there in t.parents:
            return ["DENY: " + str(target) + " is the repo-side copy of a Two-Way "
                    "Doc Mirror route — edit the vault original under "
                    + e.get("here", "?") + " instead; `code sync` transports it "
                    "(mirror declared in " + e.get("anchor", "?") + ")."]
    return []


def body_R_code_mirror_02(ctx):
    ev = getattr(ctx, "event", None)
    target = getattr(ev, "target", None) if ev else None
    if not target:
        return []
    import json
    from pathlib import Path
    idx = Path.home() / ".config/anchor-system/mirror-routes.json"
    if not idx.is_file():
        return []
    try:
        routes = json.loads(idx.read_text()).get("routes", [])
    except Exception:
        return []
    try:
        t = Path(target).resolve()
    except OSError:
        t = Path(target)
    for e in routes:
        if e.get("direction") == "pull":
            continue
        there = Path(e.get("there", ""))
        if t == there or there in t.parents:
            return ["DENY: " + str(target) + " sits inside a Two-Way Doc Mirror's "
                    "repo-side route — create/overwrite the file under "
                    + e.get("here", "?") + " in the vault instead; `code sync` "
                    "transports it (mirror declared in " + e.get("anchor", "?") + ")."]
    return []


def body_R_dispatch_guard_01(ctx):
    ev = getattr(ctx, "event", None)
    inp = getattr(ev, "input", None) or {}
    fp = inp.get("file_path") or ""
    if not fp.lower().endswith((".md", ".markdown")):
        return []
    proposed = inp.get("content")
    # Cheap gate: no identity cell, no masthead, no fire.
    if not isinstance(proposed, str) or "-[[" not in proposed:
        return []
    try:
        from pathlib import Path
        import warden_docfire as wdf
        wdf.refresh_audit_plan()
        ap = wdf.ap
        p = Path(fp)
        after = ap.masthead_narrative_offenders(proposed, p.stem)
        if not after:
            return []
        # NO ratchet (removed 2026-08-22, the ATT.md escape): a Write emits the
        # whole masthead, so legacy prose rides along in the proposed bytes and
        # is refused with it — touch means clean. Body-only work belongs in
        # the Edit tool, which passes when the spine region is untouched.
        new = after
        anchor = next((d for d in [p.parent, *p.parent.parents]
                       if (d / ".anchor").is_file()), None)
        if anchor is not None:
            excs, _, _ = ap.load_exceptions(anchor)
            if excs and (ap._exception_for(excs, "R-dispatch-table-06", p, anchor)
                         or ap._exception_for(excs, "R-dispatch-guard-01", p, anchor)):
                return []
        rows = "; ".join(f"{lbl} row: {right[:70]!r}" for lbl, right in new[:3])
        return ["DENY: this write emits a spine carrying more than 2 words in a "
                "row — " + rows + ". Touch means clean: every offending cell "
                "must be legal in the same write, legacy ones included "
                "(R-dispatch-table-06; Dan 2026-08-22: 'a hard rule that says you "
                "can't write a spine that has more than 2 words in a row'). "
                "Move each sentence to the destination page's own head/description "
                "or this doc's ## Overview (`warden mend R-dispatch-table-06`), "
                "then rewrite the rows as pure links — or use the Edit tool for "
                "body-only changes, which passes when the spine is untouched. "
                "Deliberate deviation → a graded row (A–C) in the anchor's "
                "`{slug} Exceptions.md`."]
    except Exception:
        return []  # fail-open: a guard bug must never block a write


def body_R_dispatch_guard_02(ctx):
    ev = getattr(ctx, "event", None)
    inp = getattr(ev, "input", None) or {}
    fp = inp.get("file_path") or ""
    if not fp.lower().endswith((".md", ".markdown")):
        return []
    old = inp.get("old_string") or ""
    new_s = inp.get("new_string") or ""
    if not old:
        return []
    try:
        from pathlib import Path
        p = Path(fp)
        if not p.is_file():
            return []
        text = p.read_text(encoding="utf-8")
        # Cheap gate: masthead identity cell in neither the file nor the
        # insertion → this edit cannot mint a masthead cell.
        if "-[[" not in text and "-[[" not in new_s:
            return []
        if old not in text:
            return []  # the Edit tool will reject this call itself
        proposed = (text.replace(old, new_s) if inp.get("replace_all")
                    else text.replace(old, new_s, 1))
        import warden_docfire as wdf
        wdf.refresh_audit_plan()
        ap = wdf.ap
        after = ap.masthead_narrative_offenders(proposed, p.stem)
        if not after:
            return []
        # NO per-cell ratchet (removed 2026-08-22, the ATT.md escape: adding a
        # clean row beside two legacy-illegal cells sailed through). The gate
        # is now the masthead REGION: a body-only edit leaves the spine's rows
        # byte-identical and passes even on a dirty doc — the moment the edit
        # changes any spine row, the whole spine must come out legal.
        if ap._masthead_rows(proposed, p.stem) == ap._masthead_rows(text, p.stem):
            return []
        new = after
        anchor = next((d for d in [p.parent, *p.parent.parents]
                       if (d / ".anchor").is_file()), None)
        if anchor is not None:
            excs, _, _ = ap.load_exceptions(anchor)
            if excs and (ap._exception_for(excs, "R-dispatch-table-06", p, anchor)
                         or ap._exception_for(excs, "R-dispatch-guard-02", p, anchor)):
                return []
        rows = "; ".join(f"{lbl} row: {right[:70]!r}" for lbl, right in new[:3])
        return ["DENY: this edit touches a spine that carries more than 2 words "
                "in a row — " + rows + ". Touch means clean: an edit that "
                "changes any spine row must leave the WHOLE spine legal, legacy "
                "cells included (R-dispatch-table-06; Dan 2026-08-22: 'a hard "
                "rule that says you can't write a spine that has more than 2 "
                "words in a row'). Clean the offending cells in this same edit — "
                "move each sentence to the destination page's own head/description "
                "or this doc's ## Overview (`warden mend R-dispatch-table-06`) and "
                "leave pure links. Deliberate deviation → a graded row (A–C) in "
                "the anchor's `{slug} Exceptions.md`."]
    except Exception:
        return []  # fail-open: a guard bug must never block an edit


def body_R_dispatch_guard_03(ctx):
    ev = getattr(ctx, "event", None)
    inp = getattr(ev, "input", None) or {}
    cmd = inp.get("command") or ""
    # Cheap gates: a command that names no .md file, or carries no masthead
    # identity cell in its payload, cannot be a masthead write we can see.
    if ".md" not in cmd or "-[[" not in cmd or "|" not in cmd:
        return []
    try:
        from pathlib import Path
        import os
        import re
        # .md target tokens, quoted-aware (vault paths carry spaces).
        toks = re.findall(r"'([^']+)'|\"([^\"]+)\"|(\S+)", cmd)
        cands = []
        for a, b, c in toks:
            t = (a or b or c).strip("<>|;&()`,:=")
            if t.lower().endswith((".md", ".markdown")) and t not in cands:
                cands.append(t)
        if not cands:
            return []
        import warden_docfire as wdf
        wdf.refresh_audit_plan()
        ap = wdf.ap
        # The session's cwd, for relative targets. os.getcwd() would be the
        # DAEMON's cwd (the ATT T183 lesson: daemon-process state is never the
        # caller's); the event's session mapping carries the right one.
        sess = getattr(getattr(ctx, "agent", None), "_session", None) or {}
        sess_cwd = sess.get("cwd") or ""
        for t in cands:
            t = os.path.expanduser(os.path.expandvars(t))
            p = Path(t)
            if not p.is_absolute():
                if not sess_cwd:
                    continue  # cannot resolve a relative target — leave it to
                              # the post-hoc doc-fire rather than guess
                p = Path(sess_cwd) / p
            stem = p.stem
            # Only a payload carrying THIS file's own identity cell is testable
            # — i.e. a full-masthead write (heredoc / echo of a whole table).
            if f"-[[{stem}" not in cmd and f"-[[ {stem}" not in cmd:
                continue
            after = ap.masthead_narrative_offenders(cmd, stem)
            if not after:
                continue
            # NO ratchet (removed 2026-08-22): this leg only sees full-masthead
            # writes, and writing the whole spine while any cell is illegal is
            # the violation itself — even a byte-identical re-emit of legacy
            # prose. Touch means clean.
            new = after
            base = p.parent  # p is absolute by here (relative targets skipped)
            anchor = next((d for d in [base, *base.parents]
                           if (d / ".anchor").is_file()), None)
            if anchor is not None:
                excs, _, _ = ap.load_exceptions(anchor)
                if excs and (ap._exception_for(excs, "R-dispatch-table-06", p, anchor)
                             or ap._exception_for(excs, "R-dispatch-guard-03", p, anchor)):
                    continue
            rows = "; ".join(f"{lbl} row: {right[:70]!r}" for lbl, right in new[:3])
            return ["DENY: this command writes prose into a dispatch-table RIGHT "
                    "cell of " + p.name + " — " + rows + ". A spine right cell "
                    "never carries more than 2 words in a row — links, code "
                    "spans, and <=2-word tags only (R-dispatch-table-06). "
                    "Move the sentence to the destination "
                    "page's own head/description or the doc's ## Overview "
                    "(`warden mend R-dispatch-table-06`), then write the row as "
                    "pure links — and prefer the Edit/Write tools over shell "
                    "redirection for markdown. Deliberate deviation → a graded "
                    "row (A–C) in the anchor's `{slug} Exceptions.md`."]
        return []
    except Exception:
        return []  # fail-open: a guard bug must never block a command


def body_R_dispatch_guard_04(ctx):
    ev = getattr(ctx, "event", None)
    inp = getattr(ev, "input", None) or {}
    cmd = inp.get("command") or ""
    if ".md" not in cmd:
        return []
    # Write-indicator tokens: the command itself carries a raw write mechanism.
    # Sanctioned generators (state, md-toc, audit-dispatch, queries-render)
    # pass naturally — their command lines name a script, not a write call.
    inds = ("write_text(", ".write(", "writelines", "sed -i", "perl -i",
            "tee ", "shutil.", "os.rename", "os.replace", ">>", ">")
    if not any(i in cmd for i in inds) and " mv " not in f" {cmd}"             and " cp " not in f" {cmd}" and not cmd.startswith(("mv ", "cp ")):
        return []
    try:
        from pathlib import Path
        import os
        import re
        # Quoted spans are scanned ANYWHERE in the command — not only at
        # whitespace boundaries — because the escape this rule closes names
        # its target as pathlib.Path('OBS Setup.md'): a greedy \S+ token walk
        # eats straight through those quotes and never sees the filename.
        cands = []
        for pat in (r"'([^']+\.(?:md|markdown))'",
                    r'"([^"]+\.(?:md|markdown))"'):
            for t in re.findall(pat, cmd, re.I):
                if t not in cands:
                    cands.append(t)
        for t in re.findall(r"(\S+)", cmd):
            t = t.strip("<>|;&()`,:='\"")
            if t.lower().endswith((".md", ".markdown")) and t not in cands:
                cands.append(t)
        if not cands:
            return []
        import warden_docfire as wdf
        wdf.refresh_audit_plan()
        ap = wdf.ap
        sess = getattr(getattr(ctx, "agent", None), "_session", None) or {}
        sess_cwd = sess.get("cwd") or ""
        # Follow `cd` inside the command (the R-ob-commons lesson, 7882d729):
        # the escape's real shape is `cd '<dir>'; python3 - <<PY ...
        # Path('OBS Setup.md')` — relative to the cd target, NOT the session
        # cwd, and resolving against the session cwd finds nothing and
        # fail-opens. Best-effort: the LAST cd before the write wins.
        eff_cwd = sess_cwd
        cds = re.findall(r"(?:^|[;&|]|&&|\|\|)\s*cd\s+(?:'([^']+)'"
                         r"|\"([^\"]+)\"|([^\s;&|]+))", cmd)
        if cds:
            a, b, c = cds[-1]
            # expandvars first (R-ob-commons 7882d729's other half): the
            # live escape wrote `cd "$HOME/ob/..."` — a literal $HOME that
            # expanduser alone never resolves.
            d = os.path.expanduser(os.path.expandvars(a or b or c))
            if not os.path.isabs(d) and eff_cwd:
                d = os.path.join(eff_cwd, d)
            if os.path.isdir(d):
                eff_cwd = d
        for t in cands:
            t = os.path.expanduser(os.path.expandvars(t))
            p = Path(t)
            if not p.is_absolute():
                # Try the cd-derived cwd first, then the session cwd.
                resolved = None
                for base in (eff_cwd, sess_cwd):
                    if base and (Path(base) / p).is_file():
                        resolved = Path(base) / p
                        break
                if resolved is None:
                    continue
                p = resolved
            if not p.is_file():
                continue
            try:
                disk = p.read_text(encoding="utf-8")
            except OSError:
                continue
            # Only spine-bearing pages, and only while the DISK spine is
            # already illegal. A write mechanism aimed at such a page cannot
            # be inspected pre-hoc (the content is computed at run time), so
            # while the spine is dirty the opaque channel is closed entirely.
            offenders = ap.masthead_narrative_offenders(disk, p.stem)
            if not offenders:
                continue
            # A genuinely read-only naming of the file beside an unrelated
            # redirect is the accepted false-positive cost; the deny message
            # names the clean escape (Edit/Write) in one line.
            anchor = next((d for d in [p.parent, *p.parent.parents]
                           if (d / ".anchor").is_file()), None)
            if anchor is not None:
                excs, _, _ = ap.load_exceptions(anchor)
                if excs and (ap._exception_for(excs, "R-dispatch-table-06", p, anchor)
                             or ap._exception_for(excs, "R-dispatch-guard-04", p, anchor)):
                    continue
            rows = "; ".join(f"{lbl} row: {right[:60]!r}"
                             for lbl, right in offenders[:2])
            return ["DENY: " + p.name + " carries an ILLEGAL spine (more than 2 "
                    "words in a row — " + rows + "), and this command writes it "
                    "through a channel the guard cannot inspect (inline python / "
                    "sed -i / redirect / mv). While the spine is dirty, opaque "
                    "writes to the page are refused outright — this is the exact "
                    "channel Atticus used to keep editing an illegal spine on "
                    "2026-08-22. Clean the spine FIRST via the Edit tool (move "
                    "each sentence to the destination page's own head/description "
                    "or this doc's ## Overview — `warden mend R-dispatch-table-06` "
                    "— leaving pure links), then the page is writable again. "
                    "Deliberate deviation → a graded row (A–C) in the anchor's "
                    "`{slug} Exceptions.md`."]
        return []
    except Exception:
        return []  # fail-open: a guard bug must never block a command


def guard_R_fct_claude_01(ctx):
    import datetime
    import json
    import re
    file = getattr(ctx, 'file', None)
    agent = getattr(ctx, 'agent', None)
    event = getattr(ctx, 'event', None)
    anchor = getattr(ctx, 'anchor', None)
    git = getattr(ctx, 'git', None)
    today = datetime.date.today()
    now = datetime.datetime.now()
    try:
        return bool((file.path != anchor.root.rstrip('/') + '/CLAUDE.md'))
    except Exception:
        return False


def guard_R_fct_claude_02(ctx):
    import datetime
    import json
    import re
    file = getattr(ctx, 'file', None)
    agent = getattr(ctx, 'agent', None)
    event = getattr(ctx, 'event', None)
    anchor = getattr(ctx, 'anchor', None)
    git = getattr(ctx, 'git', None)
    today = datetime.date.today()
    now = datetime.datetime.now()
    try:
        return bool(('You are the Pilot' in file.text and not file.lines[0].startswith('You are the Pilot')))
    except Exception:
        return False


def guard_R_fct_claude_03(ctx):
    import datetime
    import json
    import re
    file = getattr(ctx, 'file', None)
    agent = getattr(ctx, 'agent', None)
    event = getattr(ctx, 'event', None)
    anchor = getattr(ctx, 'anchor', None)
    git = getattr(ctx, 'git', None)
    today = datetime.date.today()
    now = datetime.datetime.now()
    try:
        return bool((not file.section('Mission') or not file.section('Mission').strip()))
    except Exception:
        return False


def guard_R_fct_claude_04(ctx):
    import datetime
    import json
    import re
    file = getattr(ctx, 'file', None)
    agent = getattr(ctx, 'agent', None)
    event = getattr(ctx, 'event', None)
    anchor = getattr(ctx, 'anchor', None)
    git = getattr(ctx, 'git', None)
    today = datetime.date.today()
    now = datetime.datetime.now()
    try:
        return bool((bool(re.search(r'^:>>', file.text, re.M))))
    except Exception:
        return False


def body_R_commit_discipline_06(ctx):

    _ROOTS = ("~/ob/grove", "~/ob/proj", "~/ob/bin")   # proj is the draining legacy root; drops out when empty
    _WINDOW = 12 * 3600
    _MAX_PATHS = 5


    def _repos():
        out = []
        for root in _ROOTS:
            root = os.path.expanduser(root)
            if os.path.isdir(os.path.join(root, ".git")):
                out.append(root)
                continue
            if not os.path.isdir(root):
                continue
            for name in sorted(os.listdir(root)):
                cand = os.path.join(root, name)
                if os.path.isdir(os.path.join(cand, ".git")):
                    out.append(cand)
        return out


    lines = []
    for repo in _repos():
        try:
            r = subprocess.run(["git", "-C", repo, "status", "--porcelain"],
                               capture_output=True, text=True, timeout=5)
        except Exception as exc:
            lines.append(f"  · {repo} — could not be polled ({type(exc).__name__})")
            continue
        if r.returncode != 0:
            continue
        paths = [ln[3:].strip().strip('"') for ln in r.stdout.splitlines() if ln[3:].strip()]
        if not paths:
            continue
        newest = 0.0
        for rel in paths:
            try:
                newest = max(newest, os.path.getmtime(os.path.join(repo, rel)))
            except OSError:
                continue          # deleted path — its mtime is gone, not evidence of staleness
        if newest and (time.time() - newest) > _WINDOW:
            continue              # older than the window — ATT F047's nightly sweep owns it
        shown = ", ".join(paths[:_MAX_PATHS])
        more = f" (+{len(paths) - _MAX_PATHS} more)" if len(paths) > _MAX_PATHS else ""
        lines.append(f"  · {repo} — {len(paths)} uncommitted: {shown}{more}")
    if not lines:
        return []
    return ("[warden] uncommitted work in a satellite repo — commit it in the turn you touched it "
            "(commit only, never push; answer a half-finished edit rather than sweeping it in):\n"
            + "\n".join(lines))


def body_R_ios_01(ctx):
    ev = getattr(ctx, "event", None)
    inp = getattr(ev, "input", None) or {}
    cmd = inp.get("command") or ""
    import re
    # Self-gate: only Apple signing/build tooling — never prose or other builds.
    if not re.search(r"\b(xcodebuild|codesign|xcrun)\b", cmd):
        return []
    adhoc = (
        re.search(r"""CODE_SIGN_IDENTITY\s*=\s*["']?-["']?(\s|$)""", cmd)
        or re.search(r"\bcodesign\b[^\n;|&]*\s(?:-s|--sign)\s+(?:-|'-'|\"-\")(\s|$)", cmd)
        or re.search(r"CODE_SIGNING_(?:REQUIRED|ALLOWED)\s*=\s*NO\b", cmd)
    )
    if not adhoc:
        return []
    return ["DENY: ad-hoc code signing is forbidden (R-ios-01) — every rebuild mints a new "
            "signing identity, so TCC permission grants (Accessibility, Screen Recording, "
            "Automation) silently reset; known-buggy from experience. Sign with the user's "
            "Apple Developer account instead: set DEVELOPMENT_TEAM to the real team and use "
            "an Apple Development certificate (`xcodebuild ... DEVELOPMENT_TEAM=<team> "
            "CODE_SIGN_STYLE=Automatic`)."]


def body_R_ios_02(ctx):
    ev = getattr(ctx, "event", None)
    target = getattr(ev, "target", None) if ev else None
    if not target:
        return []
    from pathlib import Path
    name = Path(target).name
    if not (name.endswith(".pbxproj") or name.endswith(".xcconfig")):
        return []
    inp = getattr(ev, "input", None) or {}
    new = inp.get("new_string") or ""
    import re
    adhoc = (
        re.search(r"""CODE_SIGN_IDENTITY\s*=\s*["']?-["']?\s*;?\s*$""", new, re.M)
        or re.search(r"CODE_SIGNING_(?:REQUIRED|ALLOWED)\s*=\s*NO\b", new)
    )
    if not adhoc:
        return []
    return ["DENY: this edit writes an ad-hoc signing setting into a project file "
            "(R-ios-02) — same failure as R-ios-01 at the config layer. Set "
            "DEVELOPMENT_TEAM to the user's Apple Developer team with "
            "CODE_SIGN_STYLE = Automatic instead."]


def body_R_ios_03(ctx):
    ev = getattr(ctx, "event", None)
    inp = getattr(ev, "input", None) or {}
    cmd = inp.get("command") or ""
    import re
    gui_test = (
        re.search(r"\bxcodebuild\b[^\n;|&]*\btest(?:-without-building)?\b", cmd)
        or re.search(r"\bxcrun\s+simctl\b[^\n;|&]*\b(boot|launch|ui)\b", cmd)
        or re.search(r"\bXCUITest\b", cmd)
    )
    if not gui_test:
        return []
    return ["GUI-affecting test run (R-ios-03): simulator boots and UI automation seize the "
            "local screen and focus. Favor dispatching this to a Claude bridge agent on a "
            "remote test machine via the /bridge skill; run locally only when the user "
            "expects the takeover."]


def body_R_masterguard_01(ctx):
    ev = getattr(ctx, "event", None)
    inp = getattr(ev, "input", None) or {}
    cmd = inp.get("command") or ""
    # Cheap reject first: this rule fires on every Bash call in the vault.
    if "__MASTERS__" not in cmd:
        return []

    import os
    import re
    import shlex

    # `__MASTERS__` at the VOLUME ROOT means "this drive IS the master" — the
    # discipline is Disk Conventions', not this rule's invention. A clone holds
    # the same subtree one level down (`Clone of 10T/__MASTERS__/`) and is NOT
    # the master, so it must pass: otherwise this rule would deny the very
    # clone-the-master procedure (P2) it exists to protect the source of.
    MASTER = re.compile(r"^/Volumes/([^/]+)/__MASTERS__(/|$)")

    def vol_of(tok):
        m = MASTER.match(tok.strip("'\"<>"))
        return m.group(1) if m else None

    def split(s):
        try:
            return shlex.split(s)
        except ValueError:
            return s.split()          # unparseable quoting — deny-side conservative

    SEPS = (";", "&&", "||", "|", "&")

    def segments(words, depth=0):
        """Simple commands, including those nested inside quoted payloads.

        Most master work reaches the drive through the bridge, as
        `ssh host "tmux send-keys -t w 'rm -rf /Volumes/10T/__MASTERS__/x' Enter"`.
        After one shlex pass the whole remote command is ONE token, so a rule
        that only looked at top-level tokens would see no master path at all and
        wave through exactly the commands that matter most. Recurse into any
        token that still mentions a master path. Two levels covers the bridge
        form; the bound stops a pathological string from spinning.
        """
        cur = []
        for w in words:
            if w in SEPS:
                if cur:
                    yield cur
                cur = []
                continue
            cur.append(w)
            if depth < 3 and "__MASTERS__" in w and vol_of(w) is None:
                inner = split(w)
                if inner != [w]:
                    for seg in segments(inner, depth + 1):
                        yield seg
        if cur:
            yield cur

    # Verbs whose destination is the LAST non-flag argument. Reading FROM the
    # master is always allowed, which is why position matters and mere mention
    # does not: `cp /Volumes/10T/__MASTERS__/x /tmp/` is a read.
    DEST_LAST = ("cp", "mv", "rsync", "ditto", "install", "scp")
    # Verbs that mutate every path they are handed.
    ANY_ARG = ("rm", "rmdir", "unlink", "shred", "truncate", "mkdir", "touch",
               "chmod", "chown", "chflags", "ln", "mkfifo", "tee")

    # Glued redirects (`>/Volumes/...`) split so the target is its own token.
    flat = []
    for w in split(cmd):
        if w[:1] == ">" and len(w.lstrip(">")) > 0:
            flat.append(">>" if w[:2] == ">>" else ">")
            flat.append(w.lstrip(">"))
        else:
            flat.append(w)

    hits = []
    for seg in segments(flat):
        for k, w in enumerate(seg):
            if w in (">", ">>") and k + 1 < len(seg):
                v = vol_of(seg[k + 1])
                if v:
                    hits.append((v, "a shell redirect into the master"))
        base = os.path.basename(seg[0].strip("'\""))
        args = [a for a in seg[1:] if a not in (">", ">>")]
        nonflag = [a for a in args if a[:1] != "-"]
        if base in DEST_LAST and nonflag:
            v = vol_of(nonflag[-1])
            if v:
                hits.append((v, "`%s` writing INTO the master" % base))
        elif base in ANY_ARG:
            for a in args:
                v = vol_of(a)
                if v:
                    hits.append((v, "`%s` mutating a master path" % base))
        elif base == "dd":
            for a in args:
                if a.startswith("of="):
                    v = vol_of(a[3:])
                    if v:
                        hits.append((v, "`dd of=` targeting the master"))
        elif base in ("zip", "tar") and nonflag:
            v = vol_of(nonflag[0])
            if v:
                hits.append((v, "`%s` writing its archive into the master" % base))

    if not hits:
        return []

    # The escape is a deliberate physical act on the drive itself, not a flag.
    # The sentinel sits at the VOLUME ROOT, so creating it is not itself a write
    # to `__MASTERS__` and this rule does not lock the agent out of opening one.
    # Disk Procedures P4 removes it at close-out; a sentinel left behind is a
    # finding master_sweep reports.
    #
    # **Ask the machine that actually holds the drive.** The command-parsing
    # half above is already bridge-aware — `segments()` recurses into a nested
    # `tmux send-keys` payload precisely because that is how master work
    # reaches the drive. The sentinel check was not, and the asymmetry made the
    # whole rule look complete while it answered a question nobody asked: this
    # body runs inside the laptop's resident daemon, and 10T is mounted on
    # Dexter. A local `os.path.exists` therefore returns False for every
    # correctly-opened bridged session — denying honest work, which is what
    # teaches an agent to route around a guard — and, worse, returns True if
    # this machine ever mounts a volume of the same name carrying a stale
    # sentinel, passing a write aimed at a different machine's drive. Found
    # 2026-08-21 while running Disk Procedures P1/P5 for real over the bridge;
    # ATT T261.
    def remote_target(words):
        """The host in a remote-shell invocation, or None if there is none."""
        TAKES_ARG = "bcDEeFIiJLlmOopQRSWw"
        for k, w in enumerate(words):
            if os.path.basename(w.strip("'\"")) != "s" + "sh":
                continue
            skip = False
            for a in words[k + 1:]:
                if skip:
                    skip = False
                    continue
                if a[:1] == "-":
                    skip = len(a) == 2 and a[1:2] in TAKES_ARG
                    continue
                return a.strip("'\"").split("@")[-1]
            return None
        return None

    HOST = remote_target(flat)
    _seen = {}

    def session_open(vol):
        """True / False / None — None means 'cannot judge from here'."""
        if vol in _seen:
            return _seen[vol]
        sentinel = "/Volumes/%s/.write-session" % vol
        if os.path.ismount("/Volumes/%s" % vol):
            _seen[vol] = os.path.exists(sentinel)
        elif HOST:
            import subprocess
            try:
                r = subprocess.run(
                    ["s" + "sh", "-o", "BatchMode=yes", "-o", "ConnectTimeout=4",
                     HOST, "test -e %s" % shlex.quote(sentinel)],
                    capture_output=True, timeout=8)
                _seen[vol] = (r.returncode == 0)
            except Exception:
                _seen[vol] = None
        else:
            _seen[vol] = None
        return _seen[vol]

    # Three outcomes, and the third must not silently collapse into the second.
    unknown = [h for h in hits if session_open(h[0]) is None]
    hits = [h for h in hits if session_open(h[0]) is False]
    if unknown and not hits:
        vol, why = unknown[0]
        return ["DENY: %s. /Volumes/%s is not mounted here and this command "
                "names no remote host, so whether a write session is open on "
                "that drive CANNOT BE CHECKED from this machine — and an "
                "unverifiable session is not an open one (Disk Procedures "
                "P1/P5). This is NOT the same as 'no session'. If the drive is "
                "on another machine, drive the write through the bridge so the "
                "host is named in the command, and open the session there: "
                "  echo \"$(date -u +%%FT%%TZ) <who> <why>\" > "
                "/Volumes/%s/.write-session" % (why, vol, vol)]
    if not hits:
        return []

    vol, why = hits[0]
    return ["DENY: %s. /Volumes/%s/__MASTERS__/ is a WRITE-ONCE surface — content "
            "at a path never changes, and every write goes through a deliberate "
            "session so the ledger's write-ahead row lands first (Disk Procedures "
            "P1/P5). Nothing here is a formality: a 15.4 GB abandoned scratch file "
            "sat on this drive for seven weeks and was found by accident, and an "
            "overwrite is worse than that because the ledger keeps asserting the "
            "OLD checksum afterwards. To proceed, open a session on the drive: "
            "  echo \"$(date -u +%%FT%%TZ) <who> <why>\" > /Volumes/%s/.write-session "
            "and close it with Disk Procedures P4 (master_sweep, then remove the "
            "sentinel) before unmounting." % (why, vol, vol)]


def body_R_ob_browser_lease_01(ctx):
    ev = getattr(ctx, "event", None)
    inp = getattr(ev, "input", None) or {}
    cmd = inp.get("command") or ""
    if "open" not in cmd and "osascript" not in cmd:
        return []
    import json, time, shlex

    # A human shell is never gated, and it needs no check to stay that way:
    # Dan's own `open -a Safari` is typed into Terminal and produces no hook
    # event at all, so this body never runs for him. (ctrl.py, which a human
    # DOES invoke, has to test `CLAUDECODE` explicitly for the same exemption.)
    #
    # 🚨 And do NOT reach for os.environ here to identify the caller. Python
    # rule bodies execute inside the resident warden daemon, whose environment
    # belongs to whichever session started it — `CLAUDECODE` is always set there
    # and `CLAUDE_CODE_SESSION_ID` is somebody else's. This rule shipped that way
    # for one revision and denied the very session that held the lease, because
    # it was comparing the holder against the daemon's owner. `ctx.agent` is the
    # only view bound to the session under judgement.

    # Tokenize shell-aware, and match `open` / `osascript` only in COMMAND
    # position — the lesson R-ob-remote-ops-01 and -02 each had to learn the
    # hard way, once from prose containing "; ssh ..." and once from an echo
    # that merely MENTIONED job-wrapper.sh. A rule that reads prose as code has
    # a hole that widens every time somebody writes about the rule.
    try:
        words = shlex.split(cmd)
    except ValueError:
        words = cmd.split()

    BROWSERS = ("safari", "chrome", "chromium", "firefox", "opera", "brave", "arc")

    def _cmd_position(k, w):
        return k == 0 or words[k - 1][-1:] in (";", "&", "|", "(")

    def _drives_browser():
        for k, w in enumerate(words):
            base = w.rsplit("/", 1)[-1]
            if not _cmd_position(k, w):
                continue
            if base == "open":
                rest = words[k + 1:]
                for i, t in enumerate(rest):
                    low = t.lower()
                    # `open -a Safari` / `open -b com.apple.Safari`
                    if t in ("-a", "-b") and i + 1 < len(rest):
                        nxt = rest[i + 1].lower()
                        if any(b in nxt for b in BROWSERS):
                            return True
                    # `open https://…` — no -a, but the default handler IS a
                    # browser, so the same shared surface moves.
                    if low.startswith(("http://", "https://")):
                        return True
            if base == "osascript":
                payload = " ".join(words[k + 1:]).lower()
                # Match the APP NAME, not a prefix of it: `tell application
                # "Google Chrome"` must fire, and a prefix test on "chrome"
                # silently misses it (it did, on the first run of this rule's
                # own fixtures). `application "System Events"` must not fire.
                import re as _re
                for name in _re.findall(r'application(?:\s+id)?\s+"([^"]*)"', payload):
                    if any(b in name for b in BROWSERS):
                        return True
                    if name.startswith("com.apple.safari") or \
                            name.startswith("com.google.chrome"):
                        return True
        return False

    if not _drives_browser():
        return []

    agent = getattr(ctx, "agent", None)
    session = getattr(agent, "session_id", "") or ""

    lease = None
    try:
        with open("/tmp/ctrl-browser.lease.json") as f:
            lease = json.load(f)
    except Exception:
        lease = None

    if session and lease and lease.get("session_id") == session \
            and time.time() < lease.get("deadline", 0):
        return []  # we hold it — proceed

    if not session:
        # Unbound: no session is attached to this event, so there is no way to
        # ask whether the caller is the holder. Fail closed — the resource is a
        # physical surface somebody may be looking at, and "I could not tell"
        # is not a reason to let a navigation through.
        return ["DENY: cannot identify the session behind this browser command, "
                "so it cannot be checked against the `ctrl` browser lease. "
                "Drive the browser through `ctrl` (which holds the lease itself) "
                "rather than around it. ATT T183 gap 1."]

    if lease is None:
        who = "nobody holds it"
    elif time.time() >= lease.get("deadline", 0):
        who = "the lease has EXPIRED and was never released by %s" % (
            lease.get("agent") or "an unlabelled session")
    else:
        who = "%s holds it — \"%s\"" % (lease.get("agent") or "another session",
                                        lease.get("reason") or "no reason given")

    return ["DENY: this host's browser is a single shared surface and you do not "
            "hold it (%s). Claim it first: `ctrl own [minutes] --reason \"...\"`, "
            "and `ctrl release` when done — expiry is an error path, not a release "
            "path. `ctrl lease` says who has it. This rule exists because the lease "
            "inside ctrl does not cover `open -a Safari` or osascript DOM extraction, "
            "and that path is the sanctioned one for login-walled sites — the most "
            "sensitive browsing there is. ATT T183 gap 1." % who]


def body_R_ob_commons_01(ctx):
    import os, shlex
    from pathlib import Path

    ev = getattr(ctx, "event", None)
    inp = getattr(ev, "input", None) or {}
    cmd = inp.get("command") or ""
    if "git" not in cmd:
        return []

    # The repos whose history is machine-owned. Paths, not names: a worktree or
    # a symlinked alias resolves into one of these or it does not.
    #
    # Each member carries the sentence describing THE SWEEP THAT ACTUALLY COVERS
    # IT, because they differ and a guard whose explanation is false teaches the
    # agent to distrust the guard. The vault is swept hourly and pushed; ~/ob/bin
    # is swept daily and never pushed. Telling a bin author "an hourly sweep
    # pushes everything" would be two lies in one clause.
    COMMONS = {
        Path.home() / "ob" / "kmr":
            "an hourly `km` sweep commits and pushes everything",
        Path.home() / "ob" / "grove" / "commons":
            "an hourly `km` sweep commits and pushes everything",
        Path.home() / "ob" / "bin":
            "the daily `repo_sweep` (run by `ob_daily`) commits everything, and "
            "restic snapshots every 10 minutes -- note it does NOT push, so this "
            "repo's commits stay on this machine",
    }

    try:
        words = shlex.split(cmd)
    except ValueError:
        words = cmd.split()

    # `git` in COMMAND position only — never `echo "git commit"`, never a
    # --grep=commit search, never a path that happens to contain the word.
    starts = [k for k, w in enumerate(words)
              if (w == "git" or w.endswith("/git"))
              and (k == 0 or words[k - 1][-1:] in (";", "&", "|", "("))]
    if not starts:
        return []

    # The session's cwd, not os.getcwd() -- the latter is the DAEMON's, which is
    # never the caller's (the ATT T183 lesson, same as R-dispatch-guard).
    sess = getattr(getattr(ctx, "agent", None), "_session", None) or {}
    sess_cwd = sess.get("cwd") or ""

    # Subcommands that WRITE shared history. Reads are untouched on purpose:
    # `git show HEAD:path` is how an agent undoes its own mistake, and costs
    # nothing when unused.
    WRITES = {"commit", "push", "revert", "reset", "rebase", "merge", "cherry-pick"}
    # Flags that consume the next token, so its value is never read as the
    # subcommand or as a -C path.
    ARGFUL = {"-C", "-c", "--git-dir", "--work-tree", "--namespace", "--exec-path"}

    # A `cd` earlier in the SAME command line moves the base for every git that
    # follows it.  Without this the rule judged by session cwd alone, which is
    # wrong in both directions: `cd ~/ob/grove/warden && git commit` was denied
    # (false positive, hit live 2026-08-22), and `cd ~/ob/kmr && git commit`
    # from outside would have passed (false negative -- the one that matters).
    cd_base = None
    for k, w in enumerate(words):
        if w == "cd" and (k == 0 or words[k - 1][-1:] in (";", "&", "|", "(")) \
                and k + 1 < len(words) and not words[k + 1].startswith("-"):
            cd_base = words[k + 1]

    for k in starts:
        toks = words[k + 1:]
        target, sub, i = None, None, 0
        while i < len(toks):
            t = toks[i]
            if t == "-C" and i + 1 < len(toks):
                target = toks[i + 1]
                i += 2
                continue
            if t in ARGFUL:
                i += 2
                continue
            if t.startswith("-"):
                i += 1
                continue
            sub = t
            break
        if sub not in WRITES:
            continue

        base = target or cd_base or sess_cwd
        if not base:
            continue  # cannot resolve where this would run -- don't guess
        try:
            # expandvars as well as expanduser: a command written
            # `git -C "$HOME/ob/kmr/..." commit` reaches here with $HOME
            # UNEXPANDED (shlex does not expand, expanduser only knows ~).
            # Left unhandled it resolved to a nonexistent path, whose
            # .git walk climbed out to the vault and denied a NESTED repo
            # -- the exact false positive this rule must not produce.
            here = Path(os.path.expandvars(os.path.expanduser(base))).resolve()
        except OSError:
            continue
        # Resolve the ENCLOSING REPO, not the path prefix.  Five separate git
        # repos live inside the vault -- dans-anchor-system, Career Agents,
        # SV/ww/SVAI, the HookAnchor website, an Obsidian plugin -- and every
        # one of them is a satellite that KEEPS the commit-in-the-turn norm.
        # A path-prefix test would have silently blocked all five, which is the
        # opposite of what this rule is for.  km handles them as EXTRA_REPOS.
        # An UNRESOLVABLE target is never denied.  A shell variable the rule
        # cannot see -- `git -C "$D" commit`, D set earlier in the same line --
        # survives shlex and expandvars as the literal `$D` and resolves to a
        # path that does not exist.  Walking up from a phantom lands in the
        # vault and denies a satellite (hit live 2026-08-22, on two different
        # variables).  Failing OPEN here is deliberate: this guard exists to
        # break a habit, not to defeat a determined bypass, and a false
        # positive blocking legitimate satellite work costs far more than a
        # false negative letting one commit through.
        if not here.exists():
            continue
        repo = None
        probe = here
        while True:
            if (probe / ".git").exists():
                repo = probe
                break
            if probe.parent == probe:
                break
            probe = probe.parent
        if repo is None:
            continue  # not in a repo at all -- nothing to guard
        for root, sweep in COMMONS.items():
            try:
                rroot = root.resolve()
            except OSError:
                continue
            if repo == rroot:
                return ["DENY: `git %s` inside %s -- this repo is COMMONS: its history "
                        "is machine-owned. %s, so your work IS being saved; you do not "
                        "commit it, and there is no attribution by design. Reads "
                        "(`git show`, `git log`, `git diff`) are still open -- use them "
                        "freely. Record WHY a change was made where the change lives -- "
                        "a dated bullet, a `## History` line, the BRIEF, or for a script, "
                        "a comment and its module doc -- because there is no commit "
                        "message to carry it. "
                        "See ~/ob/kmr/CLAUDE.md -- The commons: you do not commit here."
                        % (sub, str(rroot).replace(str(Path.home()), "~"), sweep)]
    return []


def body_R_ob_osascript_01(ctx):
    ev = getattr(ctx, "event", None)
    inp = getattr(ev, "input", None) or {}
    cmd = inp.get("command") or ""
    if "osascript" not in cmd or "Mail" not in cmd:
        return []
    import re, shlex

    def payloads(s, depth=0, out=None):
        # Every osascript payload, including one nested inside a quoted
        # `tmux send-keys ...` argument -- the census found real calls in
        # exactly that shape. Command-position only: `grep osascript notes.md`
        # must never read as an invocation, the lesson R-ob-remote-ops-01 and
        # -02 each had to learn separately.
        out = [] if out is None else out
        try:
            ws = shlex.split(s)
        except ValueError:
            ws = s.split()
        for k, w in enumerate(ws):
            if (w == "osascript" or w.endswith("/osascript")) and (
                    k == 0 or ws[k - 1][-1:] in (";", "&", "|", "(")):
                out.append(" ".join(ws[k + 1:]))
            elif depth < 2 and " " in w and "osascript" in w:
                payloads(w, depth + 1, out)
        return out

    for p in payloads(cmd):
        if not re.search(r'tell\s+application\s+"Mail"', p, re.I):
            continue
        # Composing has NO wrapper -- osascript is the only way to send mail
        # from here, so it is not denied. Only reads are.
        if re.search(r"make\s+new\s+outgoing\s+message|outgoing\s+message", p, re.I):
            continue
        if not re.search(r"\bwhose\b|subject\s+of|sender\s+of|content\s+of|"
                         r"\bmessages\b|\bmailboxes\b|\bcount\b", p, re.I):
            continue
        return ["DENY: searching Mail with AppleScript -> use the notmuch index: "
                "notmuch search 'from:x and date:2026-08-01..' (Xapian syntax; "
                "--format=json to parse, --output=files for Maildir paths). "
                "It answers in ~15 ms where a `whose` sweep takes minutes to hours, "
                "spans every mirrored account in ONE query, needs no auth and no GUI, "
                "and does not tie up the user's own Mail.app. "
                "A NONZERO count is not coverage -- check recency before believing a "
                "miss: `mailsync --status` names any account that is stale or has no "
                "credential. Composing/sending mail is NOT denied by this rule; there "
                "is no wrapper for it yet."]
    return []


def body_R_ob_osascript_02(ctx):
    ev = getattr(ctx, "event", None)
    inp = getattr(ev, "input", None) or {}
    cmd = inp.get("command") or ""
    if "osascript" not in cmd:
        return []
    import re, shlex

    def payloads(s, depth=0, out=None):
        out = [] if out is None else out
        try:
            ws = shlex.split(s)
        except ValueError:
            ws = s.split()
        for k, w in enumerate(ws):
            if (w == "osascript" or w.endswith("/osascript")) and (
                    k == 0 or ws[k - 1][-1:] in (";", "&", "|", "(")):
                out.append(" ".join(ws[k + 1:]))
            elif depth < 2 and " " in w and "osascript" in w:
                payloads(w, depth + 1, out)
        return out

    BROWSERS = (r'"(Safari|Google Chrome|Google Chrome Beta|Google Chrome Canary|'
                r'Brave Browser|Chromium|Firefox)"')
    for p in payloads(cmd):
        if not re.search(r"tell\s+application\s+(id\s+)?" + BROWSERS, p, re.I):
            continue
        if re.search(r"do\s+javascript|execute\s+javascript", p, re.I):
            return ["DENY: running JavaScript in a browser via AppleScript -> use ctrl. "
                    "`ctrl cpage <tab|url>` extracts a page through Chrome CDP against "
                    "your REAL Chrome (so it inherits logged-in sessions), `ctrl cexec` "
                    "runs JS there, and `ctrl jpage <url>` is the Safari equivalent. "
                    "These return structured JSON instead of a string you re-parse, and "
                    "they do not depend on Safari's AllowJavaScriptFromAppleEvents being "
                    "set. Claim the browser lease first (`ctrl own`) -- it is one surface "
                    "per machine. Tab INVENTORY and quit/activate are not denied; nothing "
                    "covers those yet."]
        if re.search(r"set\s+URL\b|open\s+location|make\s+new\s+tab|"
                     r"make\s+new\s+document", p, re.I):
            return ["DENY: navigating a browser via AppleScript -> use ctrl. "
                    "`ctrl surf <url>` (new tab), `ctrl tab <url>` (new tab, keeps "
                    "focus), `ctrl navigate <url>` (current tab), `ctrl new-tab`. "
                    "Claim the browser lease first (`ctrl own`). Tab inventory and "
                    "quit/activate are not denied; nothing covers those yet."]
    return []


def body_R_ob_osascript_03(ctx):
    ev = getattr(ctx, "event", None)
    inp = getattr(ev, "input", None) or {}
    cmd = inp.get("command") or ""
    if "osascript" not in cmd or "System Events" not in cmd:
        return []
    import re, shlex

    def payloads(s, depth=0, out=None):
        out = [] if out is None else out
        try:
            ws = shlex.split(s)
        except ValueError:
            ws = s.split()
        for k, w in enumerate(ws):
            if (w == "osascript" or w.endswith("/osascript")) and (
                    k == 0 or ws[k - 1][-1:] in (";", "&", "|", "(")):
                out.append(" ".join(ws[k + 1:]))
            elif depth < 2 and " " in w and "osascript" in w:
                payloads(w, depth + 1, out)
        return out

    for p in payloads(cmd):
        if "System Events" not in p:
            continue
        if re.search(r"\bkeystroke\b|\bkey\s+code\b", p, re.I):
            return ["DENY: synthesising keystrokes with System Events -> use "
                    "`ctrl screen type \"<text>\"` / `ctrl screen key <keyspec>` "
                    "(return, cmd+j, esc). System Events' keystroke DROPS CHARACTERS "
                    "under load -- a recorded failure in this estate -- and it types "
                    "into whatever happens to be frontmost, which is how a line lands in "
                    "someone's half-written command. NEVER inject keystrokes blind: "
                    "confirm what is focused first (`ctrl screen grab`). If the target is "
                    "a tmux pane, drive it with tmux send-keys, not the GUI."]
        # Coordinate clicks have a wrapper; AX-targeted clicks (click button "OK",
        # click menu item ...) do NOT -- `ctrl screen click` takes points, and
        # nothing walks the accessibility tree. Denying those would deny the only
        # route that exists.
        if re.search(r"\bclick\s+at\b", p, re.I):
            return ["DENY: clicking by coordinate with System Events -> use "
                    "`ctrl screen click X Y` (logical points; --px for pixels, --right, "
                    "--double). Pair it with `ctrl screen grab` and `ctrl screen size` so "
                    "the coordinates come from what is actually on screen rather than "
                    "from assumption. Clicking a NAMED element (click button \"OK\", "
                    "click menu item) is not denied -- nothing covers the accessibility "
                    "tree yet."]
    return []


def body_R_ob_osascript_04(ctx):
    ev = getattr(ctx, "event", None)
    inp = getattr(ev, "input", None) or {}
    cmd = inp.get("command") or ""
    import re, shlex
    GLANCE = ("Glance a note by opening the FILE -- `open \"/abs/path/to/Note.md\"`. "
              "Obsidian Double Click is the registered handler for .md, so that lands "
              "the note in a NEW TAB in Dan's own Obsidian (measured 2026-08-28: "
              "18 tabs -> 19). Know it only by name? `open \"$(ha -p 'Some Note')\"`. "
              "A path has nothing to remember; the URI it replaced carried TWO "
              "load-bearing parameters and agents kept dropping one of them.")

    # A heredoc body is DATA, not command position. Strip it before anything
    # else looks at the string -- otherwise writing documentation ABOUT this
    # rule trips this rule, which is exactly what happened to
    # R-ob-remote-ops-01 (TINK T609) and then, within the hour, to the first
    # cut of THIS rule while it was being written up. A guard that cannot be
    # described without firing is a guard people learn to disable.
    scan = re.sub(r"<<-?\s*'?\"?(\w+)'?\"?\n.*?\n\1\b", " ", cmd, flags=re.S)

    if "osascript" in scan:
        def payloads(s, depth=0, out=None):
            out = [] if out is None else out
            try:
                ws = shlex.split(s)
            except ValueError:
                ws = s.split()
            for k, w in enumerate(ws):
                if (w == "osascript" or w.endswith("/osascript")) and (
                        k == 0 or ws[k - 1][-1:] in (";", "&", "|", "(")):
                    out.append(" ".join(ws[k + 1:]))
                elif depth < 2 and " " in w and "osascript" in w:
                    payloads(w, depth + 1, out)
            return out
        for p in payloads(scan):
            if re.search(r'tell\s+application\s+(id\s+)?"Obsidian"', p, re.I):
                return ["DENY: driving Obsidian with AppleScript. " + GLANCE]

    # `obsidian://` needs no osascript, so it is checked separately -- but only
    # as a genuine ARGUMENT, never as text. The URI must be a whole token (after
    # quote-stripping), which is what separates `open "obsidian://open?..."` from
    # a sentence that merely names the scheme. Same discipline as command-position
    # matching above; the difference is that here the token IS the payload.
    try:
        words = shlex.split(scan)
    except ValueError:
        words = scan.split()
    for w in words:
        if not re.match(r"obsidian://", w, re.I):
            continue
        return ["DENY: hand-built obsidian:// URI. " + GLANCE +
                " Advanced-URI command execution (commandid=, eval=) is "
                "remote-controlling Dan's editor and is never the answer; a bare "
                "obsidian://open is worse than useless -- it does not open a tab at "
                "all, it REPLACES the contents of the focused one, which is the "
                "CMX P0001 clobber that destroyed his reading position for months. "
                "The whole URI surface is retired for agents: open the file."]
    return []


def body_R_ob_remote_ops_01(ctx):
    ev = getattr(ctx, "event", None)
    inp = getattr(ev, "input", None) or {}
    cmd = inp.get("command") or ""
    if "ssh" not in cmd:
        return []
    # A heredoc BODY is data, not command position — and it is where an agent
    # writes *about* commands, so tokenizing it reads documentation as
    # execution. Bodies fed to a shell are kept, because there it really is
    # code. T609; the helper carries the reasoning.
    try:
        import warden_fire as _wf
        cmd = _wf.strip_heredoc_bodies(cmd)
    except Exception:
        pass                              # deny-side conservative: judge the raw text
    # Tokenize shell-aware (shlex): a quoted string is ONE token, so prose
    # mentioning `; ssh …` inside an argument never reads as a command-position
    # ssh (live false-positive 2026-07-06 — a --body text containing
    # "IR; ssh one-shot" was denied). Unparseable quoting falls back to a
    # whitespace split (deny-side conservative).
    import shlex
    try:
        words = shlex.split(cmd)
    except ValueError:
        words = cmd.split()
    # ssh flags that take a separate value (must not be mistaken for the host)
    argful = {"-p", "-i", "-l", "-o", "-F", "-J", "-L", "-R", "-D", "-W",
              "-E", "-b", "-c", "-e", "-m", "-B", "-I", "-P", "-S", "-w"}
    # ssh as a command word: first token, or right after a separator — never
    # scp/rsync (different words), never `which ssh` / quoted mentions.
    starts = [k for k, w in enumerate(words)
              if (w == "ssh" and (k == 0 or words[k - 1][-1:] in (";", "&", "|", "(")))
              or w.endswith(("(ssh", "`ssh"))]  # $(ssh …) / `ssh …` substitution
    for k in starts:
        toks = words[k + 1:]
        host, remote = None, []
        i = 0
        while i < len(toks):
            t = toks[i]
            if t.startswith("-"):
                i += 2 if t in argful else 1
                continue
            host, remote = t, toks[i + 1:]
            break
        if host is None or not remote:
            continue  # bare interactive `ssh <host>` — a legitimate attach
        rc = remote[0].strip("'\"")
        if " " in rc or len(remote) == 1:
            # A quoted remote command is ONE token after the outer shlex.split
            # (e.g. `ssh host "tmux send-keys -t '...' '...' Enter"`) — retokenize
            # just that token to find its actual first word.
            #
            # Keyed on "remote[0] looks like a command line", NOT on it being the
            # last token. Gating on `len(remote) == 1` alone meant anything AFTER
            # the quoted command — a redirect, a pipe, a `; sleep` — left rc as
            # the whole string, so the tmux exemption below silently missed and
            # the bridge's own documented read surface was denied:
            #     ssh h "tmux capture-pane -t w -p" 2>&1 | tail -4   → DENIED
            #     ssh h "tmux capture-pane -t w -p"                  → allowed
            # Same command, opposite verdict, decided by a trailing pipe — and
            # every real read is piped. Found 2026-08-13 driving a Linux rig.
            try:
                parts = shlex.split(remote[0])
            except ValueError:
                parts = remote[0].split()
            rc = parts[0] if parts else ""
        if rc == "tmux":
            continue  # the bridge's own control plane (attach/send-keys/capture-pane)
        return ["DENY: Remote-control work → use the `bridge` skill (persistent tmux; "
                "the remote tmux inherits TCC/FDA from its launching Terminal). "
                "Don't one-shot SSH — every call re-establishes nothing, long jobs need "
                "nohup hacks, and the user can't observe it. "
                "See ~/.claude/skills/bridge/SKILL.md."]
    return []


def body_R_ob_remote_ops_02(ctx):
    ev = getattr(ctx, "event", None)
    inp = getattr(ev, "input", None) or {}
    cmd = inp.get("command") or ""
    if "tmux" not in cmd:
        return []
    # A heredoc BODY is data, not command position — and it is where an agent
    # writes *about* commands, so tokenizing it reads documentation as
    # execution. Bodies fed to a shell are kept, because there it really is
    # code. T609; the helper carries the reasoning.
    try:
        import warden_fire as _wf
        cmd = _wf.strip_heredoc_bodies(cmd)
    except Exception:
        pass                              # deny-side conservative: judge the raw text
    import shlex
    try:
        _words = shlex.split(cmd)
    except ValueError:
        _words = cmd.split()

    def _tokens(ws):
        # Nested quoted payloads (`ssh host "tmux new-window -d ..."`) are ONE
        # token after the outer split; retokenize them so the inner words are
        # visible whichever quoting form was used.
        out = list(ws)
        for w in ws:
            if " " in w and ("tmux" in w or "job-wrapper" in w):
                try:
                    out.extend(shlex.split(w))
                except ValueError:
                    out.extend(w.split())
        return out

    _flat = _tokens(_words)
    # The launcher itself launches detached -- that is its job. It identifies
    # itself by the wrapper it invokes, matched as a whole PATH TOKEN.
    #
    # A substring test (`"job-wrapper.sh" in cmd`) is what this first shipped
    # with and it was wrong within the hour: a command whose `echo` text merely
    # MENTIONED job-wrapper.sh exempted the entire compound command, detached
    # launch and all (caught 2026-08-09 by a test whose spoof case quietly
    # passed). Same failure R-ob-remote-ops-01 already had to fix for prose
    # containing "; ssh ..." -- a rule that reads prose as code is a rule with
    # a hole in it that widens every time someone writes about the rule.
    if any(w.endswith("job-wrapper.sh") and "/" in w for w in _flat):
        return []
    # Stated-reason escape. A bare --force becomes reflex; a sentence does not.
    # Same shape as --why-ask / --why-user / --why-user-action elsewhere in the
    # estate: proceed, but leave an auditable record of the judgement.
    import re
    if re.search(r"#\s*oneshot:\s*\S", cmd):
        return []
    flat = _flat
    detached = False
    for k, w in enumerate(flat):
        if w != "tmux":
            continue
        rest = flat[k + 1:]
        if not rest:
            continue
        sub = rest[0]
        if sub in ("new-window", "new-session", "new") and "-d" in rest:
            detached = True
            break
    if not detached:
        return []
    return ["DENY: launching detached remote work → use `bridge run` "
            "(~/.claude/skills/bridge/bridge run <host> --job <name> --script <path>). "
            "It wraps the WHOLE job in caffeinate, records the job's process group, "
            "and arms the liveness watch as part of starting it — so `bridge jobs <host>` "
            "can tell a silent-but-working job from a wedged one. "
            "A hand-rolled `tmux new-window -d` gives none of that: on 2026-08-09 one was "
            "reported as running for 105 minutes while blocked on a spun-down disk (ATT F054). "
            "For a genuinely bounded probe, append `# oneshot: <why this needs no watch>`."]


def body_R_pathguard_01(ctx):
    ev = getattr(ctx, "event", None)
    target = getattr(ev, "target", None) if ev else None
    if not target:
        return []
    from pathlib import Path
    p = Path(target)
    name = p.name
    if name.endswith(" Backlog.md"):
        # A backlog STORE, not merely a file whose name ends in " Backlog.md".
        # Two independent signals, either one sufficient: the `state:backlog`
        # stamp `state` writes into every store it manages, and the canonical
        # `{slug} Track/` home. They agree on all 42 vault instances; the OR
        # keeps a store guarded when one signal is missing.
        in_track = p.parent.name.endswith(" Track")
        stamped = False
        try:
            stamped = "state:backlog" in p.read_text(errors="replace")[:800]
        except OSError:
            stamped = True   # unreadable — guard rather than wave through
        if in_track or stamped:
            return ["DENY: " + name + " is owned by `state <define|set|resolve|remove> "
                    "<anchor> Backlog <label>` — never Edit backlog rows directly "
                    "(~/.claude/skills/workflow/scripts/state)."]
    if name.endswith(" queries.md") or name == "Q.md":
        return ["DENY: " + name + " is mechanically rendered by queries-render.py — "
                "edit the backlog rows / feature-doc Open Questions it renders from, not the page."]
    return []


def body_R_pathguard_02(ctx):
    ev = getattr(ctx, "event", None)
    target = getattr(ev, "target", None) if ev else None
    if not target:
        return []
    import re
    from pathlib import Path
    # Three feature-doc filename forms, all permanent — older docs are never
    # renamed: `F<n> — Title.md` (legacy), `{slug} F<n> — Title.md` (F298),
    # `{SLUG}<n> - Title.md` (F300, current — no `F`, ASCII hyphen). Canonical
    # copy of this grammar lives at `backlog_edit.feature_number`; rule bodies
    # are exec'd in isolation and cannot import, so it is repeated here.
    if not re.match(r"(?:(?:[A-Za-z][A-Za-z0-9]*\s+)?F\d+\s+—|[A-Za-z]+\d+\s+-\s)",
                    Path(target).name):
        return []
    inp = getattr(ev, "input", None) or {}
    old = inp.get("old_string") or ""
    new = inp.get("new_string") or ""
    # `## Resolved` was here until F291 and is now [[R-state-region]]'s (warn).
    # F305: `## Open Items` is the canonical heading; `## Open Questions` is
    # the legacy spelling, accepted forever (the writer renames on touch).
    heads = ("## Open Items", "## Open Questions")
    # Location-based, NOT substring-based (T045 defect 2): fire only when the
    # edit touches a REAL managed heading LINE — prose
    # that merely quotes the heading string inline (e.g. a `## Recovery note`
    # that mentions the managed region) must pass.
    head_re = re.compile(r"^(?:" + "|".join(re.escape(h) for h in heads) + r")[ \t]*$", re.M)
    hit = bool(head_re.search(old) or head_re.search(new))
    if not hit and old:
        try:
            text = Path(target).read_text(encoding="utf-8")
            for h in heads:
                m = re.search(r"^" + re.escape(h) + r"\s*$", text, re.M)
                if not m:
                    continue
                tail = text[m.end():]
                nxt = re.search(r"^## ", tail, re.M)
                if old in (tail[:nxt.start()] if nxt else tail):
                    hit = True
                    break
        except OSError:
            pass
    if not hit:
        return []
    return ["DENY: the open-items block (`## Open Items` / legacy `## Open Questions`) in a feature doc is owned by "
            "`state <define|set|resolve|remove> <anchor> <doc> <Q<n>|Q+>` — do not Edit the region directly."]


def body_R_pathguard_03(ctx):
    ev = getattr(ctx, "event", None)
    target = getattr(ev, "target", None) if ev else None
    if not target:
        return []
    from pathlib import Path
    p = Path(target)
    name = p.name
    if name.endswith(" queries.md") or name == "Q.md":
        return ["DENY: " + name + " is script-owned (`state <verb> <anchor> Backlog ...` / queries-render.py) — "
                "a wholesale Write bypasses the same discipline Edit is denied for."]
    if name.endswith(" Backlog.md"):
        # Same store-vs-namesake test as R-pathguard-01, with the third signal a
        # Write needs: the file may not exist yet, so the stamp is also looked
        # for in the content being written.
        in_track = p.parent.name.endswith(" Track")
        stamped = False
        try:
            stamped = "state:backlog" in p.read_text(errors="replace")[:800]
        except OSError:
            pass
        if not stamped:
            inp = getattr(ev, "input", None) or {}
            stamped = "state:backlog" in (inp.get("content") or "")[:800]
        if in_track or stamped:
            return ["DENY: " + name + " is script-owned (`state <verb> <anchor> Backlog ...`) — "
                    "a wholesale Write bypasses the same discipline Edit is denied for."]
    return []


def body_R_pathguard_04(ctx):
    ev = getattr(ctx, "event", None)
    target = getattr(ev, "target", None) if ev else None
    if not target:
        return []
    from pathlib import Path
    p = Path(target)
    if p.name == "Atlas.md" and p.parent.name == "Atlas":
        return ["DENY: Atlas.md is owned by /atlas — use `/atlas add <name>` / `/atlas update <name>`; "
                "direct writes break its alphabetical-order and routing disciplines."]
    return []


def body_R_pathguard_05(ctx):
    ev = getattr(ctx, "event", None)
    target = getattr(ev, "target", None) if ev else None
    if not target:
        return []
    import re
    from pathlib import Path
    p = Path(target)
    # Legacy / F298 slug-prefixed / F300 fused — see R-pathguard-02.
    if not re.match(r"(?:(?:[A-Za-z][A-Za-z0-9]*\s+)?F\d+\s+—|[A-Za-z]+\d+\s+-\s)",
                    p.name):
        return []
    # Doc creation is exempt — the /feature flow Writes a NEW doc's initial
    # Open Questions block. Fire only when the doc already exists on disk.
    if not p.is_file():
        return []
    inp = getattr(ev, "input", None) or {}
    content = inp.get("content") or ""

    # Region-diff, NOT a blunt "content mentions the heading" test (T045): a
    # whole-file Write that leaves the managed region byte-identical is a
    # legitimate prose rewrite and must pass; only a Write that CHANGES or
    # DROPS the region is the bypass (dropping it is exactly how Lumen F002
    # lost a pending Q2 + its resolved archive in 105094b4). A doc that merely
    # quotes the heading inline has no real region, so it never trips.
    def _regions(text):
        out = {}
        # Open block only since F291 — `## Resolved` is R-state-region's now.
        # F305: both spellings — `## Open Items` canonical, `## Open
        # Questions` legacy (the writer renames on touch).
        for m in re.finditer(r"^(## Open (?:Items|Questions))[ \t]*$", text, re.M):
            tail = text[m.end():]
            nxt = re.search(r"^## ", tail, re.M)
            out[m.group(1)] = tail[:nxt.start()] if nxt else tail
        return out

    try:
        on_disk = _regions(Path(target).read_text(encoding="utf-8"))
    except OSError:
        return []
    if not on_disk:            # nothing managed on disk → nothing to protect
        return []
    if _regions(content) == on_disk:   # region preserved verbatim → allow
        return []
    return ["DENY: the open-items block (`## Open Items` / legacy `## Open Questions`) in a feature doc is owned by "
            "`state <define|set|resolve|remove> <anchor> <doc> <Q<n>|Q+>` — this Write changes or drops "
            "the managed region. Preserve it verbatim (rewrite prose only) and route question "
            "edits through `state`."]


def body_R_query_14(ctx):
    PUSHCOMMIT = re.compile(r"(?i)\b(push|commit)\b")
    IMMEDIATE_Q = re.compile(r"^\s*-\s*\*\*Q\d+\b")

    # An Immediate Question (a user DECISION) that is about push/commit is the
    # bug — that decision belongs to the anchor's Git aspect, not the user.
    text = ctx.queries_text or ""
    hits = [ln for ln in text.splitlines()
            if IMMEDIATE_Q.match(ln) and PUSHCOMMIT.search(ln) and "?" in ln]
    if not hits:
        return []
    aspect = (ctx.git_aspect or "").lower()
    if aspect == "commit":
        steer = "commit at logical boundaries WITHOUT asking, and NEVER push — since you're asking, commit now (no push)."
    elif aspect == "push":
        steer = "commit at logical boundaries AND push, WITHOUT asking — since you're asking, commit and push now."
    elif aspect == "pr":
        steer = "commit freely on the branch and open/update the PR per policy — never ask."
    elif aspect == "nogit":
        steer = "this anchor is NoGit — there is nothing to commit/push; just drop the question."
    else:
        steer = "resolve it from the anchor's Git aspect yourself; never ask the user whether to commit/push."
    mode = ctx.git_aspect or "unknown"
    return [f"Do NOT ask the user about commit/push ({ctx.anchor}, {mode} mode): "
            f"{steer} Remove the question from queries.md."]


def body_R_state_region_01(ctx):
    ev = getattr(ctx, "event", None)
    target = getattr(ev, "target", None) if ev else None
    if not target:
        return []
    import re
    from pathlib import Path
    p = Path(target)
    name = p.name
    if not name.endswith(".md"):
        return []
    # Surfaces owned by harder R-pathguard DENY rules are not re-advised here.
    if name.endswith(" Backlog.md") or name.endswith(" queries.md"):
        return []
    inp = getattr(ev, "input", None) or {}
    old = inp.get("old_string") or ""
    new = inp.get("new_string") or ""
    heads = ("## Open Questions", "## Resolved", "## Status")
    # A feature doc's OPEN block is still R-pathguard's DENY; its `## Resolved`
    # and `## Status` moved here (warn) in F291 — so the doc is no longer
    # skipped wholesale, only the region the harder rule still covers.
    # Legacy `F<n> — Title.md`, F298 `{slug} F<n> — Title.md`, or F300
    # `{SLUG}<n> - Title.md`; all three are permanent, older docs are never
    # renamed. Canonical grammar: `backlog_edit.feature_number`.
    if re.match(r"(?:(?:[A-Za-z][A-Za-z0-9]*\s+)?F\d+\s+—|[A-Za-z]+\d+\s+-\s)", name):
        heads = ("## Resolved", "## Status")
    hit = any(h in old or h in new for h in heads)
    text = None
    if not hit and old:
        try:
            text = p.read_text(encoding="utf-8")
            for h in heads:
                m = re.search(r"^" + re.escape(h) + r"\s*$", text, re.M)
                if not m:
                    continue
                tail = text[m.end():]
                nxt = re.search(r"^## ", tail, re.M)
                if old in (tail[:nxt.start()] if nxt else tail):
                    hit = True
                    break
        except OSError:
            return []
    if not hit:
        return []
    if text is None:
        try:
            text = p.read_text(encoding="utf-8")
        except OSError:
            return []
    if not re.search(r"^\s*- \*\*[A-Z]+\d+ —|^### Q\d+\b", text, re.M):
        return []
    return ["state-managed region — `## Open Questions` / `## Resolved` / `## Status` on a "
            "doc carrying labeled items are maintained by `state <verb> <anchor> <doc> <label>` "
            "(define | set | resolve | remove); prefer it over a direct edit so the doc, "
            "backlog, queries.md, and Q.md stay locked together."]


def body_R_state_region_02(ctx):
    ev = getattr(ctx, "event", None)
    target = getattr(ev, "target", None) if ev else None
    if not target:
        return []
    import re
    from pathlib import Path
    p = Path(target)
    name = p.name
    if not name.endswith(".md") or not p.is_file():
        return []
    if name.endswith(" Backlog.md") or name.endswith(" queries.md"):
        return []
    inp = getattr(ev, "input", None) or {}
    content = inp.get("content") or ""
    heads = ("## Open Questions", "## Resolved", "## Status")
    # Legacy / F298 slug-prefixed / F300 fused — see rule 01. Open block stays
    # R-pathguard's (F291).
    if re.match(r"(?:(?:[A-Za-z][A-Za-z0-9]*\s+)?F\d+\s+—|[A-Za-z]+\d+\s+-\s)", name):
        heads = ("## Resolved", "## Status")
    if not any(h in content for h in heads):
        return []
    if not re.search(r"^\s*- \*\*[A-Z]+\d+ —|^### Q\d+\b", content, re.M):
        return []
    return ["state-managed region — `## Open Questions` / `## Resolved` / `## Status` on a "
            "doc carrying labeled items are maintained by `state <verb> <anchor> <doc> <label>` "
            "(define | set | resolve | remove); prefer it over a wholesale Write so the doc, "
            "backlog, queries.md, and Q.md stay locked together."]


def body_R_state_region_03(ctx):
    # NB: the compiler marks a rule file-bearing (and the engine binds
    # ctx.file) only when the source contains a literal `file.` reference —
    # keep the direct ctx.file.* accesses below (F215).
    if getattr(ctx, "file", None) is None:
        return []
    if not ctx.file.name.endswith(".md") or not ctx.file.exists:
        return []
    import hashlib, re
    stamp_re = re.compile(r"^<!--\s*state:q\s+([0-9a-z]{2})\s*-->$")
    lines = ctx.file.lines
    start = None
    for i, ln in enumerate(lines):
        if ln.strip() == "## Open Questions":
            start = i
            break
    if start is None:
        return []
    end = len(lines)
    for j in range(start + 1, len(lines)):
        if lines[j].startswith("## ") or (lines[j].startswith("# ")
                                          and not lines[j].startswith("## ")):
            end = j
            break
    stored = None
    for k in range(start + 1, end):
        m = stamp_re.match(lines[k].strip())
        if m:
            stored = m.group(1)
            break
    if stored is None:
        return []  # grandfathered — stampless legacy block
    content = [ln.rstrip() for ln in lines[start:end]
               if not stamp_re.match(ln.strip())]
    digest = hashlib.sha1("\n".join(content).encode("utf-8")).hexdigest()
    n = int(digest, 16) % 1296
    b36 = "0123456789abcdefghijklmnopqrstuvwxyz"
    computed = b36[n // 36] + b36[n % 36]
    if computed == stored:
        return []
    return [f"`## Open Questions` integrity stamp mismatch (stored `{stored}`, "
            f"computed `{computed}`) — this block is maintained by "
            "`state <verb> <anchor> <doc> <label>`; a hand-edit bypasses its ask-format "
            "gates. Re-issue the change through `state`, or run "
            "`state \"<doc>\" revalidate` to validate-then-restamp (F241)."]


def body_R_warden_selftest_01(ctx):


    p = os.path.join(os.environ.get("WARDEN_HOME") or os.path.expanduser("~/.warden"), "selftest.log")
    os.makedirs(os.path.dirname(p), exist_ok=True)
    rec = {"ts": round(time.time(), 3), "rule": "R-warden-selftest-01",
           "moment": getattr(ctx, "moment", "tool:post:Write"),
           "anchor": getattr(ctx, "anchor", "?")}
    with open(p, "a", encoding="utf-8") as fh:
        fh.write(json.dumps(rec) + "\n")
    return f"[warden selftest] R-warden-selftest-01 fired at {rec['moment']} in {rec['anchor']}"


def body_R_warden_selftest_02(ctx):


    p = os.path.join(os.environ.get("WARDEN_HOME") or os.path.expanduser("~/.warden"), "selftest.log")
    os.makedirs(os.path.dirname(p), exist_ok=True)
    rec = {"ts": round(time.time(), 3), "rule": "R-warden-selftest-02",
           "moment": getattr(ctx, "moment", "write:markdown"),
           "anchor": getattr(ctx, "anchor", "?")}
    with open(p, "a", encoding="utf-8") as fh:
        fh.write(json.dumps(rec) + "\n")
    return f"[warden selftest] R-warden-selftest-02 fired at {rec['moment']} in {rec['anchor']}"


def body_R_warden_selftest_03(ctx):


    p = os.path.join(os.environ.get("WARDEN_HOME") or os.path.expanduser("~/.warden"), "selftest.log")
    os.makedirs(os.path.dirname(p), exist_ok=True)
    rec = {"ts": round(time.time(), 3), "rule": "R-warden-selftest-03",
           "moment": getattr(ctx, "moment", "session:start"),
           "anchor": getattr(ctx, "anchor", "?")}
    with open(p, "a", encoding="utf-8") as fh:
        fh.write(json.dumps(rec) + "\n")
    return f"[warden selftest] R-warden-selftest-03 fired at {rec['moment']} in {rec['anchor']}"


def body_R_warden_selftest_04(ctx):


    p = os.path.join(os.environ.get("WARDEN_HOME") or os.path.expanduser("~/.warden"), "selftest.log")
    os.makedirs(os.path.dirname(p), exist_ok=True)
    rec = {"ts": round(time.time(), 3), "rule": "R-warden-selftest-04",
           "moment": getattr(ctx, "moment", "prompt:submit"),
           "anchor": getattr(ctx, "anchor", "?")}
    with open(p, "a", encoding="utf-8") as fh:
        fh.write(json.dumps(rec) + "\n")
    return f"[warden selftest] R-warden-selftest-04 fired at {rec['moment']} in {rec['anchor']}"


def body_R_warden_dev_01(ctx):
    return (
        "[warden] You are in the Warden anchor. Dev disciplines here: "
        "(1) Commit mode — commit at logical boundaries without asking, never amend, "
        "pathspec-limit so you never sweep another agent's in-flight files. "
        "(2) Before committing engine changes, run the unit suites "
        "(warden/engine/test_warden_*.py) AND the golden corpus "
        "(warden/Warden Corpus/harness/run-corpus.py, default + --engine warden); "
        "keep the Rust↔Python differential (test_warden_rust.py) green. "
        "(3) `warden off` disables Warden globally if anything here misfires."
    )


def body_R_warden_dev_02(ctx):
    import json
    import os
    from pathlib import Path
    home = Path(os.environ.get("WARDEN_HOME", str(Path.home() / ".warden")))
    try:
        ir = json.loads((home / "rules-ir.json").read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return []
    declared = set(ir.get("declared_traits") or [])
    if not declared:
        return []          # pre-F219 IR — no wiring snapshot to audit against
    exempt = {"warden-selftest"}   # hermetic test-fixture trait
    traits = ir.get("traits", {})
    reachable = set()
    for t, ids in traits.items():
        if t in declared or t in exempt:
            reachable.update(ids)
    moment_rules = {rid for ids in ir.get("moments", {}).values() for rid in ids}
    dead = sorted(moment_rules - reachable)
    if not dead:
        return []
    keyed_by = sorted({t for t, ids in traits.items()
                       for r in dead if r in ids})
    return [
        "[warden trait-reachability] dead wiring — moment rule(s) "
        + ", ".join(dead)
        + " (keyed only by undeclared trait(s) " + ", ".join(keyed_by)
        + ") can never fire live: no .anchor in the vault declares a keying trait. "
          "Adopt a trait on an anchor that wants those rules, or retire the ruleset."
    ]
